// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/chronicle.js';

/** Chronicle — Structured audit event engine */
export class ChronicleNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "chronicle",
  ) {}

  /** ACTORS — Active actors in time window */
  async actors(options?: {
    filter_args?: unknown;
  }): Promise<types.ChronicleActorsResponse> {
    const args: string[] = ["ACTORS"];
    if (options) {
      if (options.filter_args !== undefined) { args.push("FILTER_ARGS"); args.push(String(options.filter_args)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleActorsResponse>;
  }

  /** AUTH — Authenticate this connection */
  async auth(token: string): Promise<types.ChronicleAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleAuthResponse>;
  }

  /** COUNT — Count events matching filter predicates */
  async count(options?: {
    filter_args?: unknown;
  }): Promise<types.ChronicleCountResponse> {
    const args: string[] = ["COUNT"];
    if (options) {
      if (options.filter_args !== undefined) { args.push("FILTER_ARGS"); args.push(String(options.filter_args)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleCountResponse>;
  }

  /** ERRORS — Error rates by action */
  async errors(options?: {
    filter_args?: unknown;
  }): Promise<types.ChronicleErrorsResponse> {
    const args: string[] = ["ERRORS"];
    if (options) {
      if (options.filter_args !== undefined) { args.push("FILTER_ARGS"); args.push(String(options.filter_args)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleErrorsResponse>;
  }

  /** HEALTH — Health check */
  async health(): Promise<types.ChronicleHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleHealthResponse>;
  }

  /** HOTSPOTS — Top actors by event volume */
  async hotspots(options?: {
    filter_args?: unknown;
  }): Promise<types.ChronicleHotspotsResponse> {
    const args: string[] = ["HOTSPOTS"];
    if (options) {
      if (options.filter_args !== undefined) { args.push("FILTER_ARGS"); args.push(String(options.filter_args)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleHotspotsResponse>;
  }

  /** INGEST — Ingest a single structured audit event */
  async ingest(event_json: Record<string, unknown>): Promise<types.ChronicleIngestResponse> {
    const args: string[] = ["INGEST"];
    args.push(typeof event_json === 'string' ? event_json : JSON.stringify(event_json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleIngestResponse>;
  }

  /** INGEST_BATCH — Ingest multiple events in a single call */
  async ingestBatch(events_json: Record<string, unknown>): Promise<types.ChronicleIngestBatchResponse> {
    const args: string[] = ["INGEST_BATCH"];
    args.push(typeof events_json === 'string' ? events_json : JSON.stringify(events_json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleIngestBatchResponse>;
  }

  /** PING — Keepalive */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }

  /** QUERY — Query events with filter predicates */
  async query(options?: {
    filter_args?: unknown;
  }): Promise<types.ChronicleQueryResponse> {
    const args: string[] = ["QUERY"];
    if (options) {
      if (options.filter_args !== undefined) { args.push("FILTER_ARGS"); args.push(String(options.filter_args)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ChronicleQueryResponse>;
  }
}
