// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/cipher.js';

/** Cipher — Encryption-as-a-service */
export class CipherNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "cipher",
  ) {}

  /** AUTH — Authenticate the connection */
  async auth(token: string): Promise<types.CipherAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherAuthResponse>;
  }

  /** COMMAND LIST — List all supported commands */
  async commandList(): Promise<types.CipherCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherCommandListResponse>;
  }

  /** DECRYPT — Decrypt ciphertext using the embedded key version */
  async decrypt(keyring: string, ciphertext: string, options?: {
    context?: string;
  }): Promise<types.CipherDecryptResponse> {
    const args: string[] = ["DECRYPT"];
    args.push(String(keyring));
    args.push(String(ciphertext));
    if (options) {
      if (options.context !== undefined) { args.push("CONTEXT"); args.push(String(options.context)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherDecryptResponse>;
  }

  /** ENCRYPT — Encrypt plaintext with the active key version */
  async encrypt(keyring: string, plaintext: string, options?: {
    context?: string;
    key_version?: number;
    convergent?: boolean;
  }): Promise<types.CipherEncryptResponse> {
    const args: string[] = ["ENCRYPT"];
    args.push(String(keyring));
    args.push(String(plaintext));
    if (options) {
      if (options.context !== undefined) { args.push("CONTEXT"); args.push(String(options.context)); }
      if (options.key_version !== undefined) { args.push("KEY_VERSION"); args.push(String(options.key_version)); }
      if (options.convergent) args.push("CONVERGENT");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherEncryptResponse>;
  }

  /** GENERATE_DATA_KEY — Generate a data encryption key (envelope encryption pattern) */
  async generateDataKey(keyring: string, options?: {
    bits?: number;
  }): Promise<types.CipherGenerateDataKeyResponse> {
    const args: string[] = ["GENERATE_DATA_KEY"];
    args.push(String(keyring));
    if (options) {
      if (options.bits !== undefined) { args.push("BITS"); args.push(String(options.bits)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherGenerateDataKeyResponse>;
  }

  /** HEALTH — Check server health */
  async health(): Promise<types.CipherHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherHealthResponse>;
  }

  /** KEY_INFO — Get keyring metadata and key version information */
  async keyInfo(keyring: string): Promise<types.CipherKeyInfoResponse> {
    const args: string[] = ["KEY_INFO"];
    args.push(String(keyring));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherKeyInfoResponse>;
  }

  /** KEYRING CREATE — Create a new keyring with its first active key */
  async keyringCreate(name: string, algorithm: string, options?: {
    rotation_days?: number;
    drain_days?: number;
    convergent?: boolean;
  }): Promise<types.CipherKeyringCreateResponse> {
    const args: string[] = ["KEYRING", "CREATE"];
    args.push(String(name));
    args.push(String(algorithm));
    if (options) {
      if (options.rotation_days !== undefined) { args.push("ROTATION_DAYS"); args.push(String(options.rotation_days)); }
      if (options.drain_days !== undefined) { args.push("DRAIN_DAYS"); args.push(String(options.drain_days)); }
      if (options.convergent) args.push("CONVERGENT");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherKeyringCreateResponse>;
  }

  /** KEYRING LIST — List all keyring names */
  async keyringList(): Promise<types.CipherKeyringListResponse> {
    const args: string[] = ["KEYRING", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherKeyringListResponse>;
  }

  /** PING — Simple connectivity check — returns PONG */
  async ping(): Promise<types.CipherPingResponse> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherPingResponse>;
  }

  /** REWRAP — Re-encrypt ciphertext with the current active key version */
  async rewrap(keyring: string, ciphertext: string, options?: {
    context?: string;
  }): Promise<types.CipherRewrapResponse> {
    const args: string[] = ["REWRAP"];
    args.push(String(keyring));
    args.push(String(ciphertext));
    if (options) {
      if (options.context !== undefined) { args.push("CONTEXT"); args.push(String(options.context)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherRewrapResponse>;
  }

  /** ROTATE — Rotate the keyring to a new key version */
  async rotate(keyring: string, options?: {
    force?: boolean;
    dryrun?: boolean;
  }): Promise<types.CipherRotateResponse> {
    const args: string[] = ["ROTATE"];
    args.push(String(keyring));
    if (options) {
      if (options.force) args.push("FORCE");
      if (options.dryrun) args.push("DRYRUN");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherRotateResponse>;
  }

  /** SIGN — Create a detached signature */
  async sign(keyring: string, data: string): Promise<types.CipherSignResponse> {
    const args: string[] = ["SIGN"];
    args.push(String(keyring));
    args.push(String(data));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherSignResponse>;
  }

  /** VERIFY_SIGNATURE — Verify a detached signature */
  async verifySignature(keyring: string, data: string, signature: string): Promise<types.CipherVerifySignatureResponse> {
    const args: string[] = ["VERIFY_SIGNATURE"];
    args.push(String(keyring));
    args.push(String(data));
    args.push(String(signature));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CipherVerifySignatureResponse>;
  }
}
