// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/courier.js';

/** Courier — Just-in-time decryption delivery engine */
export class CourierNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "courier",
  ) {}

  /** AUTH — Authenticate the connection with a token */
  async auth(token: string): Promise<types.CourierAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierAuthResponse>;
  }

  /** CHANNEL CREATE — Create a delivery channel */
  async channelCreate(name: string, type: string, config_json: string): Promise<types.CourierChannelCreateResponse> {
    const args: string[] = ["CHANNEL", "CREATE"];
    args.push(String(name));
    args.push(String(type));
    args.push(String(config_json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelCreateResponse>;
  }

  /** CHANNEL DELETE — Delete a channel */
  async channelDelete(name: string): Promise<types.CourierChannelDeleteResponse> {
    const args: string[] = ["CHANNEL", "DELETE"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelDeleteResponse>;
  }

  /** CHANNEL GET — Get channel configuration */
  async channelGet(name: string): Promise<types.CourierChannelGetResponse> {
    const args: string[] = ["CHANNEL", "GET"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelGetResponse>;
  }

  /** CHANNEL LIST — List all channels */
  async channelList(): Promise<types.CourierChannelListResponse> {
    const args: string[] = ["CHANNEL", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelListResponse>;
  }

  /** COMMAND LIST — List available commands */
  async commandList(): Promise<types.CourierCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierCommandListResponse>;
  }

  /** DELIVER — Decrypt recipient and deliver a message */
  async deliver(json: string): Promise<types.CourierDeliverResponse> {
    const args: string[] = ["DELIVER"];
    args.push(String(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierDeliverResponse>;
  }

  /** DELIVERY GET — Get a delivery receipt by ID */
  async deliveryGet(id: string): Promise<types.CourierDeliveryGetResponse> {
    const args: string[] = ["DELIVERY", "GET"];
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierDeliveryGetResponse>;
  }

  /** DELIVERY LIST — List delivery receipts, optionally filtered by channel */
  async deliveryList(options?: {
    CHANNEL?: string;
    LIMIT?: number;
  }): Promise<types.CourierDeliveryListResponse> {
    const args: string[] = ["DELIVERY", "LIST"];
    if (options) {
      if (options.CHANNEL !== undefined) { args.push("CHANNEL"); args.push(String(options.CHANNEL)); }
      if (options.LIMIT !== undefined) { args.push("LIMIT"); args.push(String(options.LIMIT)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierDeliveryListResponse>;
  }

  /** HEALTH — Server health check */
  async health(): Promise<types.CourierHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierHealthResponse>;
  }

  /** HELLO — Engine identity handshake — returns engine name, version, wire protocol, supported commands, and capability tags. Pre-auth; clients issue this on connect to verify they are talking to the expected engine and version. */
  async hello(): Promise<types.CourierHelloResponse> {
    const args: string[] = ["HELLO"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierHelloResponse>;
  }

  /** METRICS — Get delivery metrics (total, success, failure counts, per-channel breakdown) */
  async metrics(): Promise<types.CourierMetricsResponse> {
    const args: string[] = ["METRICS"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierMetricsResponse>;
  }

  /** NOTIFY_EVENT — Trigger a notification on a pre-configured channel (e.g. rotation/expiry alerts) */
  async notifyEvent(channel: string, subject: string, body: string): Promise<types.CourierNotifyEventResponse> {
    const args: string[] = ["NOTIFY_EVENT"];
    args.push(String(channel));
    args.push(String(subject));
    args.push(String(body));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierNotifyEventResponse>;
  }

  /** PING — Connectivity check */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }
}
