// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/courier.js';

/** Courier — Just-in-time decryption delivery engine */
export class CourierNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "courier",
  ) {}

  /** AUTH — Authenticate the connection with a token */
  async auth(token: string): Promise<types.CourierAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierAuthResponse>;
  }

  /** CHANNEL CREATE — Create a delivery channel */
  async channelCreate(name: string, type: string, config_json: string): Promise<types.CourierChannelCreateResponse> {
    const args: string[] = ["CHANNEL", "CREATE"];
    args.push(String(name));
    args.push(String(type));
    args.push(String(config_json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelCreateResponse>;
  }

  /** CHANNEL DELETE — Delete a channel */
  async channelDelete(name: string): Promise<types.CourierChannelDeleteResponse> {
    const args: string[] = ["CHANNEL", "DELETE"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelDeleteResponse>;
  }

  /** CHANNEL GET — Get channel configuration */
  async channelGet(name: string): Promise<types.CourierChannelGetResponse> {
    const args: string[] = ["CHANNEL", "GET"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelGetResponse>;
  }

  /** CHANNEL LIST — List all channels */
  async channelList(): Promise<types.CourierChannelListResponse> {
    const args: string[] = ["CHANNEL", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierChannelListResponse>;
  }

  /** COMMAND LIST — List available commands */
  async commandList(): Promise<types.CourierCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierCommandListResponse>;
  }

  /** DELIVER — Decrypt recipient and deliver a message */
  async deliver(json: string): Promise<types.CourierDeliverResponse> {
    const args: string[] = ["DELIVER"];
    args.push(String(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierDeliverResponse>;
  }

  /** HEALTH — Server health check */
  async health(): Promise<types.CourierHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.CourierHealthResponse>;
  }

  /** PING — Connectivity check */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }
}
