// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/forge.js';

/** Forge — Internal certificate authority engine */
export class ForgeNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "forge",
  ) {}

  /** AUTH — Authenticate this connection with a token */
  async auth(token: string): Promise<types.ForgeAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeAuthResponse>;
  }

  /** CA CREATE — Create a new Certificate Authority */
  async caCreate(name: string, algorithm: string, subject: string, options?: {
    ttl_days?: number;
    parent?: string;
  }): Promise<types.ForgeCaCreateResponse> {
    const args: string[] = ["CA", "CREATE"];
    args.push(String(name));
    args.push(String(algorithm));
    args.push("SUBJECT");
    args.push(String(subject));
    if (options) {
      if (options.ttl_days !== undefined) { args.push("TTL_DAYS"); args.push(String(options.ttl_days)); }
      if (options.parent !== undefined) { args.push("PARENT"); args.push(String(options.parent)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCaCreateResponse>;
  }

  /** CA EXPORT — Export the active CA certificate (PEM) */
  async caExport(name: string): Promise<types.ForgeCaExportResponse> {
    const args: string[] = ["CA", "EXPORT"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCaExportResponse>;
  }

  /** CA INFO — Get CA metadata and key version status */
  async caInfo(name: string): Promise<types.ForgeCaInfoResponse> {
    const args: string[] = ["CA", "INFO"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCaInfoResponse>;
  }

  /** CA LIST — List all Certificate Authorities */
  async caList(): Promise<types.ForgeCaListResponse> {
    const args: string[] = ["CA", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCaListResponse>;
  }

  /** CA ROTATE — Rotate CA signing key */
  async caRotate(name: string, options?: {
    force?: boolean;
    dryrun?: boolean;
  }): Promise<types.ForgeCaRotateResponse> {
    const args: string[] = ["CA", "ROTATE"];
    args.push(String(name));
    if (options) {
      if (options.force) args.push("FORCE");
      if (options.dryrun) args.push("DRYRUN");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCaRotateResponse>;
  }

  /** COMMAND — List supported commands */
  async command(): Promise<types.ForgeCommandResponse> {
    const args: string[] = ["COMMAND"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeCommandResponse>;
  }

  /** CONFIG GET — Get a runtime configuration value */
  async configGet(key: string): Promise<types.ForgeConfigGetResponse> {
    const args: string[] = ["CONFIG", "GET"];
    args.push(String(key));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeConfigGetResponse>;
  }

  /** CONFIG SET — Set a runtime configuration value (only scheduler_interval_secs is mutable) */
  async configSet(key: string, value: string): Promise<types.ForgeConfigSetResponse> {
    const args: string[] = ["CONFIG", "SET"];
    args.push(String(key));
    args.push(String(value));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeConfigSetResponse>;
  }

  /** HEALTH — Health check */
  async health(): Promise<types.ForgeHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeHealthResponse>;
  }

  /** HELLO — Engine identity handshake — returns engine name, version, wire protocol, supported commands, and capability tags. Pre-auth; clients issue this on connect to verify they are talking to the expected engine and version. */
  async hello(): Promise<types.ForgeHelloResponse> {
    const args: string[] = ["HELLO"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeHelloResponse>;
  }

  /** INSPECT — Get certificate details */
  async inspect(ca: string, serial: string): Promise<types.ForgeInspectResponse> {
    const args: string[] = ["INSPECT"];
    args.push(String(ca));
    args.push(String(serial));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeInspectResponse>;
  }

  /** ISSUE — Issue a new certificate. Returns cert + private key (private key never stored). */
  async issue(ca: string, subject: string, profile: string, options?: {
    ttl?: string;
    san_dns?: unknown;
    san_ip?: unknown;
  }): Promise<types.ForgeIssueResponse> {
    const args: string[] = ["ISSUE"];
    args.push(String(ca));
    args.push(String(subject));
    args.push(String(profile));
    if (options) {
      if (options.ttl !== undefined) { args.push("TTL"); args.push(String(options.ttl)); }
      if (options.san_dns !== undefined) { args.push("SAN_DNS"); args.push(String(options.san_dns)); }
      if (options.san_ip !== undefined) { args.push("SAN_IP"); args.push(String(options.san_ip)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeIssueResponse>;
  }

  /** ISSUE_FROM_CSR — Issue a certificate from a PEM-encoded CSR */
  async issueFromCsr(ca: string, csr_pem: string, profile: string, options?: {
    ttl?: string;
  }): Promise<types.ForgeIssueFromCsrResponse> {
    const args: string[] = ["ISSUE_FROM_CSR"];
    args.push(String(ca));
    args.push(String(csr_pem));
    args.push(String(profile));
    if (options) {
      if (options.ttl !== undefined) { args.push("TTL"); args.push(String(options.ttl)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeIssueFromCsrResponse>;
  }

  /** LIST_CERTS — List certificates for a CA */
  async listCerts(ca: string, options?: {
    state?: string;
    limit?: number;
    offset?: number;
  }): Promise<types.ForgeListCertsResponse> {
    const args: string[] = ["LIST_CERTS"];
    args.push(String(ca));
    if (options) {
      if (options.state !== undefined) { args.push("STATE"); args.push(String(options.state)); }
      if (options.limit !== undefined) { args.push("LIMIT"); args.push(String(options.limit)); }
      if (options.offset !== undefined) { args.push("OFFSET"); args.push(String(options.offset)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeListCertsResponse>;
  }

  /** PING — Liveness probe. Returns PONG. */
  async ping(): Promise<types.ForgePingResponse> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgePingResponse>;
  }

  /** REGENERATE_CRL — Force regeneration of the CRL for a CA. Also accepted as `CA REGENERATE_CRL <name>`. */
  async regenerateCrl(ca: string): Promise<types.ForgeRegenerateCrlResponse> {
    const args: string[] = ["REGENERATE_CRL"];
    args.push(String(ca));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeRegenerateCrlResponse>;
  }

  /** RENEW — Renew a certificate (re-issue with same profile and SANs) */
  async renew(ca: string, serial: string, options?: {
    ttl?: string;
  }): Promise<types.ForgeRenewResponse> {
    const args: string[] = ["RENEW"];
    args.push(String(ca));
    args.push(String(serial));
    if (options) {
      if (options.ttl !== undefined) { args.push("TTL"); args.push(String(options.ttl)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeRenewResponse>;
  }

  /** REVOKE — Revoke a certificate */
  async revoke(ca: string, serial: string, options?: {
    reason?: string;
  }): Promise<types.ForgeRevokeResponse> {
    const args: string[] = ["REVOKE"];
    args.push(String(ca));
    args.push(String(serial));
    if (options) {
      if (options.reason !== undefined) { args.push("REASON"); args.push(String(options.reason)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ForgeRevokeResponse>;
  }
}
