// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/keep.js';

/** Keep — Secrets manager with path-based access control and versioning */
export class KeepNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "keep",
  ) {}

  /** AUTH — Authenticate this connection with a token. */
  async auth(token: string): Promise<types.KeepAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepAuthResponse>;
  }

  /** COMMAND LIST — List all supported commands. */
  async commandList(): Promise<types.KeepCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepCommandListResponse>;
  }

  /** DELETE — Soft-delete a secret. Version history is preserved. */
  async delete(path: string): Promise<types.KeepDeleteResponse> {
    const args: string[] = ["DELETE"];
    args.push(String(path));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepDeleteResponse>;
  }

  /** GET — Retrieve a secret value. Returns the latest version by default. */
  async get(path: string, options?: {
    version?: string;
  }): Promise<types.KeepGetResponse> {
    const args: string[] = ["GET"];
    args.push(String(path));
    if (options) {
      if (options.version !== undefined) { args.push("VERSION"); args.push(String(options.version)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepGetResponse>;
  }

  /** GET — batch variant: pipelines N independent calls over one connection (ordered, not atomic). */
  async getMany(calls: Array<{
    path: string;
    version?: string;
  }>): Promise<types.KeepGetResponse[]> {
    const argsList: string[][] = calls.map((call) => {
      const args: string[] = ["GET"];
      args.push(String(call.path));
      if (call.version !== undefined) { args.push("VERSION"); args.push(String(call.version)); }
      return args;
    });
    return this.transport.executeMany(this.engine, argsList) as unknown as Promise<types.KeepGetResponse[]>;
  }

  /** HEALTH — Health check. */
  async health(): Promise<types.KeepHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepHealthResponse>;
  }

  /** LIST — List secret paths, optionally filtered by prefix. Excludes deleted secrets. */
  async list(prefix?: string): Promise<types.KeepListResponse> {
    const args: string[] = ["LIST"];
    if (prefix !== undefined) args.push(String(prefix));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepListResponse>;
  }

  /** PING — Ping-pong. */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }

  /** PURGE — Permanently remove a secret and all its versions. Irreversible — used for GDPR right-to-erasure compliance. After purge, GET returns not-found (not deleted). */
  async purge(path: string): Promise<types.KeepPurgeResponse> {
    const args: string[] = ["PURGE"];
    args.push(String(path));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepPurgeResponse>;
  }

  /** PUT — Store a new version of a secret. Creates the secret if it doesn't exist. Undeletes if soft-deleted. */
  async put(path: string, value: string | Uint8Array): Promise<types.KeepPutResponse> {
    const args: string[] = ["PUT"];
    args.push(String(path));
    args.push(typeof value === 'string' ? value : Buffer.from(value).toString('base64'));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepPutResponse>;
  }

  /** REKEY — Re-encrypt all secrets with a new master key. Iterates all secrets (including deleted ones), decrypts every version with the current master key, re-encrypts with the new key, and switches to the new key for all future operations. */
  async rekey(new_key: string): Promise<types.KeepRekeyResponse> {
    const args: string[] = ["REKEY"];
    args.push(String(new_key));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepRekeyResponse>;
  }

  /** ROTATE — Re-encrypt the latest version with a new nonce. Creates a new version with the same plaintext. */
  async rotate(path: string): Promise<types.KeepRotateResponse> {
    const args: string[] = ["ROTATE"];
    args.push(String(path));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepRotateResponse>;
  }

  /** VERSIONS — Get version history for a secret. Includes deleted secrets. */
  async versions(path: string): Promise<types.KeepVersionsResponse> {
    const args: string[] = ["VERSIONS"];
    args.push(String(path));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.KeepVersionsResponse>;
  }
}
