// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/scroll.js';

/** Scroll — Durable append-only event log with cursored readers and reader groups */
export class ScrollNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "scroll",
  ) {}

  /** ACK — Acknowledge a pending entry. Idempotent. */
  async ack(log: string, group: string, offset: number): Promise<types.ScrollAckResponse> {
    const args: string[] = ["ACK"];
    args.push(String(log));
    args.push(String(group));
    args.push(String(offset));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollAckResponse>;
  }

  /** APPEND — Append an entry to a log. Mints a monotonic offset through the per-log serializer and encrypts the entry with the per-log DEK. */
  async append(log: string, payload_b64: unknown, options?: {
    headers?: Record<string, unknown>;
    ttl_ms?: number;
  }): Promise<types.ScrollAppendResponse> {
    const args: string[] = ["APPEND"];
    args.push(String(log));
    args.push(String(payload_b64));
    if (options) {
      if (options.headers !== undefined) { args.push("HEADERS"); args.push(typeof options.headers === 'string' ? options.headers : JSON.stringify(options.headers)); }
      if (options.ttl_ms !== undefined) { args.push("TTL_MS"); args.push(String(options.ttl_ms)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollAppendResponse>;
  }

  /** AUTH — Authenticate the connection. Consumed at the connection layer before dispatch. */
  async auth(token: string): Promise<types.ScrollAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollAuthResponse>;
  }

  /** CLAIM — Reassign stalled pending entries to a new reader. Entries whose delivery_count would cross max_delivery_count are moved to scroll.dlq instead. */
  async claim(log: string, group: string, reader_id: string, min_idle_ms: number): Promise<types.ScrollClaimResponse> {
    const args: string[] = ["CLAIM"];
    args.push(String(log));
    args.push(String(group));
    args.push(String(reader_id));
    args.push(String(min_idle_ms));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollClaimResponse>;
  }

  /** COMMAND LIST — List all supported commands with their syntax. */
  async commandList(): Promise<types.ScrollCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollCommandListResponse>;
  }

  /** CREATE_GROUP — Create a reader group. start_offset = 'earliest' | '0' starts from offset 0; 'latest' | '-1' starts after the current tail. */
  async createGroup(log: string, group: string, start_offset: string): Promise<types.ScrollCreateGroupResponse> {
    const args: string[] = ["CREATE_GROUP"];
    args.push(String(log));
    args.push(String(group));
    args.push(String(start_offset));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollCreateGroupResponse>;
  }

  /** DELETE_GROUP — Tear down a single reader group: delete every pending record, then remove the group row. Counterpart to CREATE_GROUP; doesn't touch scroll.logs or the DEK, so other groups on the same log keep operating. Returns 'group not found' when the target doesn't exist. */
  async deleteGroup(log: string, group: string): Promise<types.ScrollDeleteGroupResponse> {
    const args: string[] = ["DELETE_GROUP"];
    args.push(String(log));
    args.push(String(group));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollDeleteGroupResponse>;
  }

  /** DELETE_LOG — Hard-delete all log state (entries, groups, pending, offset counter) and destroy the wrapped DEK to crypto-shred. */
  async deleteLog(log: string): Promise<types.ScrollDeleteLogResponse> {
    const args: string[] = ["DELETE_LOG"];
    args.push(String(log));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollDeleteLogResponse>;
  }

  /** GROUP_INFO — Stats for a reader group: cursor, members, and pending entry count. */
  async groupInfo(log: string, group: string): Promise<types.ScrollGroupInfoResponse> {
    const args: string[] = ["GROUP_INFO"];
    args.push(String(log));
    args.push(String(group));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollGroupInfoResponse>;
  }

  /** HEALTH — Engine liveness probe. */
  async health(): Promise<types.ScrollHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollHealthResponse>;
  }

  /** HELLO — Engine identity + version + supported commands. Pre-auth version-detection handshake. */
  async hello(): Promise<types.ScrollHelloResponse> {
    const args: string[] = ["HELLO"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollHelloResponse>;
  }

  /** LOG_INFO — Stats for a log: entries minted, latest offset, created-at, and list of reader groups. */
  async logInfo(log: string): Promise<types.ScrollLogInfoResponse> {
    const args: string[] = ["LOG_INFO"];
    args.push(String(log));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollLogInfoResponse>;
  }

  /** PING — Connection liveness probe. Returns PONG. */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }

  /** READ — Range read starting at from_offset. Missing offsets (trimmed / TTL-expired) are skipped silently. */
  async read(log: string, from_offset: number, limit: number): Promise<types.ScrollReadResponse> {
    const args: string[] = ["READ"];
    args.push(String(log));
    args.push(String(from_offset));
    args.push(String(limit));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollReadResponse>;
  }

  /** READ_GROUP — Advance the group cursor under CAS on `scroll.groups`, register PendingEntry records, and return the decrypted batch. */
  async readGroup(log: string, group: string, reader_id: string, limit: number): Promise<types.ScrollReadGroupResponse> {
    const args: string[] = ["READ_GROUP"];
    args.push(String(log));
    args.push(String(group));
    args.push(String(reader_id));
    args.push(String(limit));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollReadGroupResponse>;
  }

  /** REPLAY — Move a DLQ entry back into a group's pending set. Preserves the original reader_id from the DLQ record, resets delivery_count to 1, stamps a fresh delivered_at_ms. Put-pending-first / delete-dlq-second ordering: a crash in-between leaves a duplicate, never a loss. Returns 'dlq entry not found' when the offset has no DLQ record, 'group not found' when the target group doesn't exist. */
  async replay(log: string, group: string, offset: number): Promise<types.ScrollReplayResponse> {
    const args: string[] = ["REPLAY"];
    args.push(String(log));
    args.push(String(group));
    args.push(String(offset));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollReplayResponse>;
  }

  /** TAIL — Live tail: returns at most limit entries at or after from_offset, waiting up to TIMEOUT ms (default 30_000) for new appends. Closes with TAIL_OVERFLOW on subscribe backpressure; client should fall back to READ. */
  async tail(log: string, from_offset: number, limit: number, options?: {
    timeout_ms?: number;
  }): Promise<types.ScrollTailResponse> {
    const args: string[] = ["TAIL"];
    args.push(String(log));
    args.push(String(from_offset));
    args.push(String(limit));
    if (options) {
      if (options.timeout_ms !== undefined) { args.push("TIMEOUT_MS"); args.push(String(options.timeout_ms)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollTailResponse>;
  }

  /** TRIM — Explicit retention. MAX_LEN keeps the most recent N offsets; MAX_AGE drops entries whose appended_at_ms is older than now-ms. */
  async trim(log: string, selector: string, value: number): Promise<types.ScrollTrimResponse> {
    const args: string[] = ["TRIM"];
    args.push(String(log));
    args.push("MAX_LEN");
    args.push(String(selector));
    args.push("TRIM");
    args.push(String(value));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ScrollTrimResponse>;
  }
}
