// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/sentry.js';

/** Sentry — sentry */
export class SentryNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "sentry",
  ) {}

  /** AUTH — Authenticate the connection with a token */
  async auth(token: string): Promise<types.SentryAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryAuthResponse>;
  }

  /** COMMAND LIST — List all supported commands */
  async commandList(): Promise<types.SentryCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryCommandListResponse>;
  }

  /** EVALUATE — Evaluate an authorization request against policies and return a signed decision */
  async evaluate(json: string): Promise<types.SentryEvaluateResponse> {
    const args: string[] = ["EVALUATE"];
    args.push(String(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryEvaluateResponse>;
  }

  /** HEALTH — Server health check */
  async health(): Promise<types.SentryHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryHealthResponse>;
  }

  /** JWKS — Get the JSON Web Key Set for verifying decision tokens */
  async jwks(): Promise<types.SentryJwksResponse> {
    const args: string[] = ["JWKS"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryJwksResponse>;
  }

  /** KEY INFO — Get signing key metadata */
  async keyInfo(): Promise<types.SentryKeyInfoResponse> {
    const args: string[] = ["KEY", "INFO"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryKeyInfoResponse>;
  }

  /** KEY ROTATE — Rotate the signing key */
  async keyRotate(options?: {
    FORCE?: boolean;
    DRYRUN?: boolean;
  }): Promise<types.SentryKeyRotateResponse> {
    const args: string[] = ["KEY", "ROTATE"];
    if (options) {
      if (options.FORCE) args.push("FORCE");
      if (options.DRYRUN) args.push("DRYRUN");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryKeyRotateResponse>;
  }

  /** PING — Connectivity check */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }

  /** POLICY CREATE — Create a new authorization policy */
  async policyCreate(name: string, json: string): Promise<types.SentryPolicyCreateResponse> {
    const args: string[] = ["POLICY", "CREATE"];
    args.push(String(name));
    args.push(String(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryPolicyCreateResponse>;
  }

  /** POLICY DELETE — Delete a policy */
  async policyDelete(name: string): Promise<types.SentryPolicyDeleteResponse> {
    const args: string[] = ["POLICY", "DELETE"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryPolicyDeleteResponse>;
  }

  /** POLICY GET — Get a policy by name */
  async policyGet(name: string): Promise<types.SentryPolicyGetResponse> {
    const args: string[] = ["POLICY", "GET"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryPolicyGetResponse>;
  }

  /** POLICY LIST — List all policy names */
  async policyList(): Promise<types.SentryPolicyListResponse> {
    const args: string[] = ["POLICY", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryPolicyListResponse>;
  }

  /** POLICY UPDATE — Update an existing policy */
  async policyUpdate(name: string, json: string): Promise<types.SentryPolicyUpdateResponse> {
    const args: string[] = ["POLICY", "UPDATE"];
    args.push(String(name));
    args.push(String(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SentryPolicyUpdateResponse>;
  }
}
