// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/shroudb.js';

/** Shroudb — Encrypted key-value database */
export class ShroudbNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "shroudb",
  ) {}

  /** AUTH — Authenticate the connection with a token */
  async auth(token: string): Promise<types.ShroudbAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbAuthResponse>;
  }

  /** COMMAND LIST — List all supported commands */
  async commandList(): Promise<types.ShroudbCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbCommandListResponse>;
  }

  /** CONFIG GET — Read a runtime configuration value */
  async configGet(key: string): Promise<types.ShroudbConfigGetResponse> {
    const args: string[] = ["CONFIG", "GET"];
    args.push(String(key));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbConfigGetResponse>;
  }

  /** CONFIG SET — Set a runtime configuration value (admin only). Only registered config keys are accepted; unknown keys return an error. Values are type-checked against the key's schema (u64, bool, string). Valid keys: max_segment_bytes, max_segment_entries, snapshot_entry_threshold, snapshot_time_threshold_secs. */
  async configSet(key: string, value: string): Promise<CommandResult> {
    const args: string[] = ["CONFIG", "SET"];
    args.push(String(key));
    args.push(String(value));
    return this.transport.execute(this.engine, args);
  }

  /** DELETE — Delete a key by writing a tombstone */
  async delete(namespace: string, key: string): Promise<types.ShroudbDeleteResponse> {
    const args: string[] = ["DELETE"];
    args.push(String(namespace));
    args.push(String(key));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbDeleteResponse>;
  }

  /** GET — Retrieve the value at a key */
  async get(namespace: string, key: string, META?: boolean, options?: {
    version?: number;
  }): Promise<types.ShroudbGetResponse> {
    const args: string[] = ["GET"];
    args.push(String(namespace));
    args.push(String(key));
    if (META !== undefined) args.push(String(META));
    if (options) {
      if (options.version !== undefined) { args.push("VERSION"); args.push(String(options.version)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbGetResponse>;
  }

  /** HEALTH — Check server health */
  async health(): Promise<types.ShroudbHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbHealthResponse>;
  }

  /** LIST — List active keys in a namespace. Returns an error if the CURSOR value does not correspond to a key that exists in the namespace. */
  async list(namespace: string, options?: {
    prefix?: string;
    cursor?: string;
    limit?: number;
  }): Promise<types.ShroudbListResponse> {
    const args: string[] = ["LIST"];
    args.push(String(namespace));
    if (options) {
      if (options.prefix !== undefined) { args.push("PREFIX"); args.push(String(options.prefix)); }
      if (options.cursor !== undefined) { args.push("CURSOR"); args.push(String(options.cursor)); }
      if (options.limit !== undefined) { args.push("LIMIT"); args.push(String(options.limit)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbListResponse>;
  }

  /** NAMESPACE ALTER — Update namespace configuration (enforce-on-write-only) */
  async namespaceAlter(name: string, options?: {
    schema?: Record<string, unknown>;
    max_versions?: number;
    tombstone_retention?: number;
  }): Promise<CommandResult> {
    const args: string[] = ["NAMESPACE", "ALTER"];
    args.push(String(name));
    if (options) {
      if (options.schema !== undefined) { args.push("SCHEMA"); args.push(typeof options.schema === 'string' ? options.schema : JSON.stringify(options.schema)); }
      if (options.max_versions !== undefined) { args.push("MAX_VERSIONS"); args.push(String(options.max_versions)); }
      if (options.tombstone_retention !== undefined) { args.push("TOMBSTONE_RETENTION"); args.push(String(options.tombstone_retention)); }
    }
    return this.transport.execute(this.engine, args);
  }

  /** NAMESPACE CREATE — Create a new namespace */
  async namespaceCreate(name: string, options?: {
    schema?: Record<string, unknown>;
    max_versions?: number;
    tombstone_retention?: number;
  }): Promise<CommandResult> {
    const args: string[] = ["NAMESPACE", "CREATE"];
    args.push(String(name));
    if (options) {
      if (options.schema !== undefined) { args.push("SCHEMA"); args.push(typeof options.schema === 'string' ? options.schema : JSON.stringify(options.schema)); }
      if (options.max_versions !== undefined) { args.push("MAX_VERSIONS"); args.push(String(options.max_versions)); }
      if (options.tombstone_retention !== undefined) { args.push("TOMBSTONE_RETENTION"); args.push(String(options.tombstone_retention)); }
    }
    return this.transport.execute(this.engine, args);
  }

  /** NAMESPACE DROP — Drop a namespace */
  async namespaceDrop(name: string, FORCE?: boolean): Promise<CommandResult> {
    const args: string[] = ["NAMESPACE", "DROP"];
    args.push(String(name));
    if (FORCE !== undefined) args.push(String(FORCE));
    return this.transport.execute(this.engine, args);
  }

  /** NAMESPACE INFO — Get metadata about a namespace */
  async namespaceInfo(name: string): Promise<types.ShroudbNamespaceInfoResponse> {
    const args: string[] = ["NAMESPACE", "INFO"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbNamespaceInfoResponse>;
  }

  /** NAMESPACE LIST — List namespaces (filtered by token grants) */
  async namespaceList(options?: {
    cursor?: string;
    limit?: number;
  }): Promise<types.ShroudbNamespaceListResponse> {
    const args: string[] = ["NAMESPACE", "LIST"];
    if (options) {
      if (options.cursor !== undefined) { args.push("CURSOR"); args.push(String(options.cursor)); }
      if (options.limit !== undefined) { args.push("LIMIT"); args.push(String(options.limit)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbNamespaceListResponse>;
  }

  /** NAMESPACE VALIDATE — Check existing entries against current MetaSchema */
  async namespaceValidate(name: string): Promise<types.ShroudbNamespaceValidateResponse> {
    const args: string[] = ["NAMESPACE", "VALIDATE"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbNamespaceValidateResponse>;
  }

  /** PING — Test connectivity */
  async ping(): Promise<types.ShroudbPingResponse> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbPingResponse>;
  }

  /** PIPELINE — Execute commands atomically (all succeed or all roll back) */
  async pipeline(commands: string[][], requestId?: string): Promise<CommandResult[]> {
    return this.transport.executePipeline(this.engine, commands, requestId);
  }

  /** PUT — Store a value at the given key. Auto-increments version. */
  async put(namespace: string, key: string, value?: string, options?: {
    meta?: Record<string, unknown>;
  }): Promise<types.ShroudbPutResponse> {
    const args: string[] = ["PUT"];
    args.push(String(namespace));
    args.push(String(key));
    if (value !== undefined) args.push(String(value));
    if (options) {
      if (options.meta !== undefined) { args.push("META"); args.push(typeof options.meta === 'string' ? options.meta : JSON.stringify(options.meta)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbPutResponse>;
  }

  /** REKEY — Begin online rekey (zero-downtime master key rotation) */
  async rekey(): Promise<types.ShroudbRekeyResponse> {
    const args: string[] = ["REKEY"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbRekeyResponse>;
  }

  /** REKEY STATUS — Query progress of an in-flight rekey operation */
  async rekeyStatus(): Promise<types.ShroudbRekeyStatusResponse> {
    const args: string[] = ["REKEY", "STATUS"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbRekeyStatusResponse>;
  }

  /** SUBSCRIBE — Subscribe to change events on a namespace */
  async subscribe(namespace: string, options?: {
    key?: string;
    events?: unknown;
  }): Promise<CommandResult> {
    const args: string[] = ["SUBSCRIBE"];
    args.push(String(namespace));
    if (options) {
      if (options.key !== undefined) { args.push("KEY"); args.push(String(options.key)); }
      if (options.events !== undefined) { args.push("EVENTS"); args.push(String(options.events)); }
    }
    return this.transport.execute(this.engine, args);
  }

  /** UNSUBSCRIBE — End the current subscription */
  async unsubscribe(): Promise<CommandResult> {
    const args: string[] = ["UNSUBSCRIBE"];
    return this.transport.execute(this.engine, args);
  }

  /** VERSIONS — Retrieve version history for a key (most recent first) */
  async versions(namespace: string, key: string, options?: {
    limit?: number;
    from?: number;
  }): Promise<types.ShroudbVersionsResponse> {
    const args: string[] = ["VERSIONS"];
    args.push(String(namespace));
    args.push(String(key));
    if (options) {
      if (options.limit !== undefined) { args.push("LIMIT"); args.push(String(options.limit)); }
      if (options.from !== undefined) { args.push("FROM"); args.push(String(options.from)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.ShroudbVersionsResponse>;
  }
}
