// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/sigil.js';

/** Sigil — Schema-driven credential envelope engine */
export class SigilNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "sigil",
  ) {}

  /** CREDENTIAL CHANGE — Change a credential field (requires old value for verification) */
  async credentialChange(schema: string, id: string, field: string, oldValue: string, newValue: string): Promise<types.SigilCredentialChangeResponse> {
    const args: string[] = ["CREDENTIAL", "CHANGE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(field));
    args.push(String(oldValue));
    args.push(String(newValue));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilCredentialChangeResponse>;
  }

  /** CREDENTIAL IMPORT — Import a pre-hashed credential (bcrypt, scrypt, argon2). Transparently rehashed to Argon2id on next verify. */
  async credentialImport(schema: string, id: string, field: string, hash: string, options?: {
    meta?: Record<string, unknown>;
  }): Promise<types.SigilCredentialImportResponse> {
    const args: string[] = ["CREDENTIAL", "IMPORT"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(field));
    args.push(String(hash));
    if (options) {
      if (options.meta !== undefined) { args.push("META"); args.push(typeof options.meta === 'string' ? options.meta : JSON.stringify(options.meta)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilCredentialImportResponse>;
  }

  /** CREDENTIAL RESET — Force-reset a credential field without requiring old value (admin/reset token) */
  async credentialReset(schema: string, id: string, field: string, newValue: string): Promise<types.SigilCredentialResetResponse> {
    const args: string[] = ["CREDENTIAL", "RESET"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(field));
    args.push(String(newValue));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilCredentialResetResponse>;
  }

  /** ENVELOPE CREATE — Create an envelope with field routing per schema kind */
  async envelopeCreate(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilEnvelopeCreateResponse> {
    const args: string[] = ["ENVELOPE", "CREATE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeCreateResponse>;
  }

  /** ENVELOPE DELETE — Delete an envelope and all associated data */
  async envelopeDelete(schema: string, id: string): Promise<types.SigilEnvelopeDeleteResponse> {
    const args: string[] = ["ENVELOPE", "DELETE"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeDeleteResponse>;
  }

  /** ENVELOPE GET — Get an envelope record */
  async envelopeGet(schema: string, id: string): Promise<types.SigilEnvelopeGetResponse> {
    const args: string[] = ["ENVELOPE", "GET"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeGetResponse>;
  }

  /** ENVELOPE IMPORT — Import an envelope with pre-hashed credential fields. Non-credential fields processed normally. */
  async envelopeImport(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilEnvelopeImportResponse> {
    const args: string[] = ["ENVELOPE", "IMPORT"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeImportResponse>;
  }

  /** ENVELOPE LOOKUP — Look up an envelope by indexed or searchable field value */
  async envelopeLookup(schema: string, field: string, value: string): Promise<types.SigilEnvelopeLookupResponse> {
    const args: string[] = ["ENVELOPE", "LOOKUP"];
    args.push(String(schema));
    args.push(String(field));
    args.push(String(value));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeLookupResponse>;
  }

  /** ENVELOPE UPDATE — Update non-credential fields on an existing envelope */
  async envelopeUpdate(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilEnvelopeUpdateResponse> {
    const args: string[] = ["ENVELOPE", "UPDATE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeUpdateResponse>;
  }

  /** ENVELOPE VERIFY — Verify a credential field on an envelope by explicit field name */
  async envelopeVerify(schema: string, id: string, field: string, value: string): Promise<types.SigilEnvelopeVerifyResponse> {
    const args: string[] = ["ENVELOPE", "VERIFY"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(field));
    args.push(String(value));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilEnvelopeVerifyResponse>;
  }

  /** HEALTH — Health check */
  async health(): Promise<types.SigilHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilHealthResponse>;
  }

  /** JWKS — Get the JSON Web Key Set for external token verification */
  async jwks(schema: string): Promise<types.SigilJwksResponse> {
    const args: string[] = ["JWKS"];
    args.push(String(schema));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilJwksResponse>;
  }

  /** PASSWORD CHANGE — Sugar: change password. Infers credential field from schema. Equivalent to CREDENTIAL CHANGE with implicit field. */
  async passwordChange(schema: string, id: string, oldValue: string, newValue: string): Promise<types.SigilPasswordChangeResponse> {
    const args: string[] = ["PASSWORD", "CHANGE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(oldValue));
    args.push(String(newValue));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilPasswordChangeResponse>;
  }

  /** PASSWORD IMPORT — Sugar: import pre-hashed password. Infers credential field from schema. Equivalent to CREDENTIAL IMPORT with implicit field. */
  async passwordImport(schema: string, id: string, hash: string, options?: {
    meta?: Record<string, unknown>;
  }): Promise<types.SigilPasswordImportResponse> {
    const args: string[] = ["PASSWORD", "IMPORT"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(hash));
    if (options) {
      if (options.meta !== undefined) { args.push("META"); args.push(typeof options.meta === 'string' ? options.meta : JSON.stringify(options.meta)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilPasswordImportResponse>;
  }

  /** PASSWORD RESET — Sugar: force-reset password. Infers credential field from schema. Equivalent to CREDENTIAL RESET with implicit field. */
  async passwordReset(schema: string, id: string, newValue: string): Promise<types.SigilPasswordResetResponse> {
    const args: string[] = ["PASSWORD", "RESET"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(newValue));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilPasswordResetResponse>;
  }

  /** SCHEMA ALTER — Add or remove fields from a schema, producing a new version. Added fields are optional (required=false). Existing envelopes remain readable. */
  async schemaAlter(name: string, action: string, options?: {
    field_json?: Record<string, unknown>;
    field_name?: string;
  }): Promise<types.SigilSchemaAlterResponse> {
    const args: string[] = ["SCHEMA", "ALTER"];
    args.push(String(name));
    args.push(String(action));
    if (options) {
      if (options.field_json !== undefined) { args.push("FIELD_JSON"); args.push(typeof options.field_json === 'string' ? options.field_json : JSON.stringify(options.field_json)); }
      if (options.field_name !== undefined) { args.push("FIELD_NAME"); args.push(String(options.field_name)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSchemaAlterResponse>;
  }

  /** SCHEMA GET — Get a schema definition by name */
  async schemaGet(name: string): Promise<types.SigilSchemaGetResponse> {
    const args: string[] = ["SCHEMA", "GET"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSchemaGetResponse>;
  }

  /** SCHEMA LIST — List all registered schema names */
  async schemaList(): Promise<types.SigilSchemaListResponse> {
    const args: string[] = ["SCHEMA", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSchemaListResponse>;
  }

  /** SCHEMA REGISTER — Register a credential envelope schema */
  async schemaRegister(name: string, json: Record<string, unknown>): Promise<types.SigilSchemaRegisterResponse> {
    const args: string[] = ["SCHEMA", "REGISTER"];
    args.push(String(name));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSchemaRegisterResponse>;
  }

  /** SESSION CREATE — Verify credentials and issue access + refresh tokens. Fields annotated with claim=true are auto-included in the JWT from the entity's envelope. Enriched claim values override caller-provided META for the same key. */
  async sessionCreate(schema: string, id: string, password: string, options?: {
    meta?: Record<string, unknown>;
  }): Promise<types.SigilSessionCreateResponse> {
    const args: string[] = ["SESSION", "CREATE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(password));
    if (options) {
      if (options.meta !== undefined) { args.push("META"); args.push(typeof options.meta === 'string' ? options.meta : JSON.stringify(options.meta)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSessionCreateResponse>;
  }

  /** SESSION LIST — List active sessions for an entity */
  async sessionList(schema: string, id: string): Promise<types.SigilSessionListResponse> {
    const args: string[] = ["SESSION", "LIST"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSessionListResponse>;
  }

  /** SESSION REFRESH — Rotate refresh token and issue new access token. Fields annotated with claim=true are re-read from the entity's current envelope, so refreshed tokens reflect the latest values (e.g. role changes). */
  async sessionRefresh(schema: string, token: string): Promise<types.SigilSessionRefreshResponse> {
    const args: string[] = ["SESSION", "REFRESH"];
    args.push(String(schema));
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSessionRefreshResponse>;
  }

  /** SESSION REVOKE — Revoke a single refresh token (logout one session) */
  async sessionRevoke(schema: string, token: string): Promise<types.SigilSessionRevokeResponse> {
    const args: string[] = ["SESSION", "REVOKE"];
    args.push(String(schema));
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSessionRevokeResponse>;
  }

  /** SESSION REVOKE ALL — Revoke all sessions for an entity (logout everywhere) */
  async sessionRevokeAll(schema: string, id: string): Promise<types.SigilSessionRevokeAllResponse> {
    const args: string[] = ["SESSION", "REVOKE ALL"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilSessionRevokeAllResponse>;
  }

  /** USER CREATE — Sugar: create an envelope. Equivalent to ENVELOPE CREATE. */
  async userCreate(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilUserCreateResponse> {
    const args: string[] = ["USER", "CREATE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserCreateResponse>;
  }

  /** USER DELETE — Sugar: delete an envelope. Equivalent to ENVELOPE DELETE. */
  async userDelete(schema: string, id: string): Promise<types.SigilUserDeleteResponse> {
    const args: string[] = ["USER", "DELETE"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserDeleteResponse>;
  }

  /** USER GET — Sugar: get an envelope. Equivalent to ENVELOPE GET. */
  async userGet(schema: string, id: string): Promise<types.SigilUserGetResponse> {
    const args: string[] = ["USER", "GET"];
    args.push(String(schema));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserGetResponse>;
  }

  /** USER IMPORT — Sugar: import an envelope with pre-hashed credentials. Equivalent to ENVELOPE IMPORT. */
  async userImport(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilUserImportResponse> {
    const args: string[] = ["USER", "IMPORT"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserImportResponse>;
  }

  /** USER UPDATE — Sugar: update non-credential fields. Equivalent to ENVELOPE UPDATE. */
  async userUpdate(schema: string, id: string, json: Record<string, unknown>): Promise<types.SigilUserUpdateResponse> {
    const args: string[] = ["USER", "UPDATE"];
    args.push(String(schema));
    args.push(String(id));
    args.push(typeof json === 'string' ? json : JSON.stringify(json));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserUpdateResponse>;
  }

  /** USER VERIFY — Sugar: verify credential. Infers the credential field from schema. Equivalent to ENVELOPE VERIFY with implicit field. */
  async userVerify(schema: string, id: string, password: string): Promise<types.SigilUserVerifyResponse> {
    const args: string[] = ["USER", "VERIFY"];
    args.push(String(schema));
    args.push(String(id));
    args.push(String(password));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.SigilUserVerifyResponse>;
  }
}
