// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/stash.js';

/** Stash — Encrypted blob storage with S3 backend and envelope encryption */
export class StashNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "stash",
  ) {}

  /** COMMAND — List supported commands */
  async command(): Promise<CommandResult> {
    const args: string[] = ["COMMAND"];
    return this.transport.execute(this.engine, args);
  }

  /** HEALTH — Health check */
  async health(): Promise<CommandResult> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args);
  }

  /** INSPECT — Read blob metadata without downloading or decrypting */
  async inspect(id: string): Promise<types.StashInspectResponse> {
    const args: string[] = ["INSPECT"];
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.StashInspectResponse>;
  }

  /** PING — Ping-pong */
  async ping(): Promise<CommandResult> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args);
  }

  /** RETRIEVE — Retrieve and decrypt a blob */
  async retrieve(id: string): Promise<CommandResult> {
    const args: string[] = ["RETRIEVE"];
    args.push(String(id));
    return this.transport.execute(this.engine, args);
  }

  /** REVOKE — Revoke a blob (hard crypto-shred by default, SOFT for soft revoke) */
  async revoke(id: string, options?: {
    soft?: boolean;
  }): Promise<types.StashRevokeResponse> {
    const args: string[] = ["REVOKE"];
    args.push(String(id));
    if (options) {
      if (options.soft) args.push("SOFT");
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.StashRevokeResponse>;
  }

  /** STORE — Store an encrypted blob */
  async store(id: string, data_b64: string, options?: {
    client_encrypted?: string;
    content_type?: string;
    keyring?: string;
  }): Promise<types.StashStoreResponse> {
    const args: string[] = ["STORE"];
    args.push(String(id));
    args.push(String(data_b64));
    if (options) {
      if (options.client_encrypted !== undefined) { args.push("CLIENT_ENCRYPTED"); args.push(String(options.client_encrypted)); }
      if (options.content_type !== undefined) { args.push("CONTENT_TYPE"); args.push(String(options.content_type)); }
      if (options.keyring !== undefined) { args.push("KEYRING"); args.push(String(options.keyring)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.StashStoreResponse>;
  }
}
