// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from '../transport/interface.js';
import type * as types from '../types/veil.js';

/** Veil — veil */
export class VeilNamespace {
  /** @internal */
  constructor(
    private readonly transport: Transport,
    private readonly engine: string = "veil",
  ) {}

  /** AUTH — Authenticate this connection */
  async auth(token: string): Promise<types.VeilAuthResponse> {
    const args: string[] = ["AUTH"];
    args.push(String(token));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilAuthResponse>;
  }

  /** COMMAND LIST — List all supported commands */
  async commandList(): Promise<types.VeilCommandListResponse> {
    const args: string[] = ["COMMAND", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilCommandListResponse>;
  }

  /** DELETE — Remove an entry's blind tokens from the index */
  async delete(index: string, id: string): Promise<types.VeilDeleteResponse> {
    const args: string[] = ["DELETE"];
    args.push(String(index));
    args.push(String(id));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilDeleteResponse>;
  }

  /** HEALTH — Health check */
  async health(): Promise<types.VeilHealthResponse> {
    const args: string[] = ["HEALTH"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilHealthResponse>;
  }

  /** INDEX CREATE — Create a new blind index with a fresh HMAC key */
  async indexCreate(name: string): Promise<types.VeilIndexCreateResponse> {
    const args: string[] = ["INDEX", "CREATE"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilIndexCreateResponse>;
  }

  /** INDEX INFO — Get information about a blind index */
  async indexInfo(name: string): Promise<types.VeilIndexInfoResponse> {
    const args: string[] = ["INDEX", "INFO"];
    args.push(String(name));
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilIndexInfoResponse>;
  }

  /** INDEX LIST — List all blind index names */
  async indexList(): Promise<types.VeilIndexListResponse> {
    const args: string[] = ["INDEX", "LIST"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilIndexListResponse>;
  }

  /** PING — Ping-pong */
  async ping(): Promise<types.VeilPingResponse> {
    const args: string[] = ["PING"];
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilPingResponse>;
  }

  /** PUT — Tokenize plaintext and store the blind tokens under the given entry ID */
  async put(index: string, id: string, plaintext_b64: string, options?: {
    field?: string;
  }): Promise<types.VeilPutResponse> {
    const args: string[] = ["PUT"];
    args.push(String(index));
    args.push(String(id));
    args.push(String(plaintext_b64));
    if (options) {
      if (options.field !== undefined) { args.push("FIELD"); args.push(String(options.field)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilPutResponse>;
  }

  /** SEARCH — Search a blind index. Tokenizes the query, generates blind tokens, and compares against stored entries. */
  async search(index: string, query: string, options?: {
    mode?: string;
    field?: string;
    limit?: number;
  }): Promise<types.VeilSearchResponse> {
    const args: string[] = ["SEARCH"];
    args.push(String(index));
    args.push(String(query));
    if (options) {
      if (options.mode !== undefined) { args.push("MODE"); args.push(String(options.mode)); }
      if (options.field !== undefined) { args.push("FIELD"); args.push(String(options.field)); }
      if (options.limit !== undefined) { args.push("LIMIT"); args.push(String(options.limit)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilSearchResponse>;
  }

  /** TOKENIZE — Generate blind tokens from plaintext without storing. Returns HMAC-derived tokens for external use. */
  async tokenize(index: string, plaintext_b64: string, options?: {
    field?: string;
  }): Promise<types.VeilTokenizeResponse> {
    const args: string[] = ["TOKENIZE"];
    args.push(String(index));
    args.push(String(plaintext_b64));
    if (options) {
      if (options.field !== undefined) { args.push("FIELD"); args.push(String(options.field)); }
    }
    return this.transport.execute(this.engine, args) as unknown as Promise<types.VeilTokenizeResponse>;
  }
}
