// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `chronicle.ACTORS()`. */
export interface ChronicleActorsResponse {
  actors: unknown[];
  status: string;
}

/** Response from `chronicle.AUTH()`. */
export interface ChronicleAuthResponse {
  status: string;
}

/** Response from `chronicle.COMMAND_LIST()`. */
export interface ChronicleCommandListResponse {
  commands: unknown[];
}

/** Response from `chronicle.COUNT()`. */
export interface ChronicleCountResponse {
  count: number;
  scanned: number;
  status: string;
}

/** Response from `chronicle.ERRORS()`. */
export interface ChronicleErrorsResponse {
  errors: unknown[];
  status: string;
}

/** Response from `chronicle.HEALTH()`. */
export interface ChronicleHealthResponse {
  events: number;
  status: string;
}

/** Response from `chronicle.HELLO()`. */
export interface ChronicleHelloResponse {
  capabilities: unknown[];
  commands: unknown[];
  engine: string;
  protocol: string;
  version: string;
}

/** Response from `chronicle.HOTSPOTS()`. */
export interface ChronicleHotspotsResponse {
  hotspots: unknown[];
  status: string;
}

/** Response from `chronicle.INGEST()`. */
export interface ChronicleIngestResponse {
  status: string;
}

/** Response from `chronicle.INGEST_BATCH()`. */
export interface ChronicleIngestBatchResponse {
  ingested: number;
  status: string;
}

/** Response from `chronicle.QUERY()`. */
export interface ChronicleQueryResponse {
  events: unknown[];
  matched: number;
  scanned: number;
  status: string;
}

/** Response from `chronicle.VERIFY()`. */
export interface ChronicleVerifyResponse {
  per_tenant: Record<string, unknown>;
  status: string;
  total: number;
  verified: number;
}

