// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `chronicle.ACTORS()`. */
export interface ChronicleActorsResponse {
  entries: unknown[];
}

/** Response from `chronicle.AUTH()`. */
export interface ChronicleAuthResponse {
  status: string;
}

/** Response from `chronicle.COUNT()`. */
export interface ChronicleCountResponse {
  count: number;
}

/** Response from `chronicle.ERRORS()`. */
export interface ChronicleErrorsResponse {
  entries: unknown[];
}

/** Response from `chronicle.HEALTH()`. */
export interface ChronicleHealthResponse {
  status: string;
}

/** Response from `chronicle.HOTSPOTS()`. */
export interface ChronicleHotspotsResponse {
  entries: unknown[];
}

/** Response from `chronicle.INGEST()`. */
export interface ChronicleIngestResponse {
  status: string;
}

/** Response from `chronicle.INGEST_BATCH()`. */
export interface ChronicleIngestBatchResponse {
  ingested: number;
  status: string;
}

/** Response from `chronicle.QUERY()`. */
export interface ChronicleQueryResponse {
  events: unknown[];
}

