// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `cipher.auth()`. */
export interface CipherAuthResponse {
  /** OK on success */
  status: string;
}

/** Response from `cipher.command_list()`. */
export interface CipherCommandListResponse {
  /** Number of supported commands */
  count: number;
  /** List of command verb strings */
  commands: unknown[];
}

/** Response from `cipher.decrypt()`. */
export interface CipherDecryptResponse {
  /** ok */
  status: string;
  /** Decrypted data */
  plaintext: string;
}

/** Response from `cipher.encrypt()`. */
export interface CipherEncryptResponse {
  /** ok */
  status: string;
  /** Encrypted data with embedded key version */
  ciphertext: string;
  /** Key version used for encryption */
  key_version: number;
}

/** Response from `cipher.generate_data_key()`. */
export interface CipherGenerateDataKeyResponse {
  /** ok */
  status: string;
  /** Plaintext DEK (use for local encryption, then discard) */
  plaintext_key: string;
  /** Wrapped DEK (store alongside ciphertext, unwrap via DECRYPT) */
  wrapped_key: string;
  /** Key version used to wrap */
  key_version: number;
}

/** Response from `cipher.health()`. */
export interface CipherHealthResponse {
  /** ok */
  status: string;
}

/** Response from `cipher.key_info()`. */
export interface CipherKeyInfoResponse {
  /** Keyring name */
  keyring: string;
  /** Keyring algorithm */
  algorithm: string;
  /** Currently active key version */
  active_version: number;
  /** List of all key versions with state */
  versions: unknown[];
}

/** Response from `cipher.keyring_create()`. */
export interface CipherKeyringCreateResponse {
  /** ok */
  status: string;
  /** Keyring name */
  keyring: string;
  /** Algorithm */
  algorithm: string;
  /** Active key version */
  active_version: number;
}

/** Response from `cipher.keyring_list()`. */
export interface CipherKeyringListResponse {
  /** Bare JSON array of keyring name strings */
  keyrings: unknown[];
}

/** Response from `cipher.ping()`. */
export interface CipherPingResponse {
  /** Always the bare string "PONG" (not wrapped in an object) */
  pong: string;
}

/** Response from `cipher.rewrap()`. */
export interface CipherRewrapResponse {
  /** ok */
  status: string;
  /** Re-encrypted ciphertext with new key version */
  ciphertext: string;
  /** New key version used */
  key_version: number;
}

/** Response from `cipher.rotate()`. */
export interface CipherRotateResponse {
  /** ok */
  status: string;
  /** Whether rotation occurred */
  rotated: boolean;
  /** Active key version after operation */
  key_version: number;
  /** Previous active key version */
  previous_version?: number;
}

/** Response from `cipher.sign()`. */
export interface CipherSignResponse {
  /** ok */
  status: string;
  /** Hex-encoded detached signature */
  signature: string;
  /** Key version used */
  key_version: number;
}

/** Response from `cipher.verify_signature()`. */
export interface CipherVerifySignatureResponse {
  /** ok */
  status: string;
  /** Whether the signature is valid */
  valid: boolean;
}

