// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `courier.AUTH()`. */
export interface CourierAuthResponse {
  status: string;
}

/** Response from `courier.CHANNEL_CREATE()`. */
export interface CourierChannelCreateResponse {
  channel_type: string;
  name: string;
  status: string;
}

/** Response from `courier.CHANNEL_DELETE()`. */
export interface CourierChannelDeleteResponse {
  name: string;
  status: string;
}

/** Response from `courier.CHANNEL_GET()`. */
export interface CourierChannelGetResponse {
  channel_type: string;
  created_at: number;
  enabled: boolean;
  name: string;
}

/** Response from `courier.CHANNEL_LIST()`. */
export interface CourierChannelListResponse {
  channels: unknown[];
  count: number;
  status: string;
}

/** Response from `courier.COMMAND_LIST()`. */
export interface CourierCommandListResponse {
  commands: unknown[];
  count: number;
}

/** Response from `courier.DELIVER()`. */
export interface CourierDeliverResponse {
  channel: string;
  delivered_at: number;
  delivery_id: string;
  status: string;
}

/** Response from `courier.DELIVERY_GET()`. */
export interface CourierDeliveryGetResponse {
  channel: string;
  delivered_at: number;
  delivery_id: string;
  error: string;
  status: string;
}

/** Response from `courier.DELIVERY_LIST()`. */
export interface CourierDeliveryListResponse {
  count: number;
  receipts: unknown[];
  status: string;
}

/** Response from `courier.HEALTH()`. */
export interface CourierHealthResponse {
  channels: number;
  status: string;
}

/** Response from `courier.METRICS()`. */
export interface CourierMetricsResponse {
  delivered: number;
  failed: number;
  per_channel: unknown;
  total_deliveries: number;
}

/** Response from `courier.NOTIFY_EVENT()`. */
export interface CourierNotifyEventResponse {
  channel: string;
  delivered_at: number;
  delivery_id: string;
  status: string;
}

