// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `forge.AUTH()`. */
export interface ForgeAuthResponse {
  status: string;
}

/** Response from `forge.CA_CREATE()`. */
export interface ForgeCaCreateResponse {
  active_version: number;
  algorithm: string;
  name: string;
  subject: string;
}

/** Response from `forge.CA_EXPORT()`. */
export interface ForgeCaExportResponse {
  certificate_pem: string;
}

/** Response from `forge.CA_INFO()`. */
export interface ForgeCaInfoResponse {
  algorithm: string;
  key_versions: unknown[];
  name: string;
  subject: string;
}

/** Response from `forge.CA_LIST()`. */
export interface ForgeCaListResponse {
  cas: unknown[];
}

/** Response from `forge.CA_ROTATE()`. */
export interface ForgeCaRotateResponse {
  key_version: number;
  previous_version: number;
  rotated: boolean;
}

/** Response from `forge.COMMAND()`. */
export interface ForgeCommandResponse {
  commands: unknown[];
}

/** Response from `forge.CONFIG_GET()`. */
export interface ForgeConfigGetResponse {
  key: string;
  status: string;
  value: unknown;
}

/** Response from `forge.CONFIG_SET()`. */
export interface ForgeConfigSetResponse {
  key: string;
  status: string;
  value: string;
}

/** Response from `forge.HEALTH()`. */
export interface ForgeHealthResponse {
  status: string;
}

/** Response from `forge.INSPECT()`. */
export interface ForgeInspectResponse {
  certificate_pem: string;
  serial: string;
  state: string;
  subject: string;
}

/** Response from `forge.ISSUE()`. */
export interface ForgeIssueResponse {
  certificate_pem: string;
  private_key_pem: string;
  serial: string;
}

/** Response from `forge.ISSUE_FROM_CSR()`. */
export interface ForgeIssueFromCsrResponse {
  certificate_pem: string;
  serial: string;
}

/** Response from `forge.LIST_CERTS()`. */
export interface ForgeListCertsResponse {
  certs: unknown[];
  count: number;
}

/** Response from `forge.PING()`. */
export interface ForgePingResponse {
  status: string;
}

/** Response from `forge.REGENERATE_CRL()`. */
export interface ForgeRegenerateCrlResponse {
  status: string;
}

/** Response from `forge.RENEW()`. */
export interface ForgeRenewResponse {
  certificate_pem: string;
  private_key_pem: string;
  serial: string;
}

/** Response from `forge.REVOKE()`. */
export interface ForgeRevokeResponse {
  status: string;
}

