// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `keep.auth()`. */
export interface KeepAuthResponse {
  status: string;
}

/** Response from `keep.command_list()`. */
export interface KeepCommandListResponse {
  count: number;
  commands: unknown[];
}

/** Response from `keep.delete()`. */
export interface KeepDeleteResponse {
  status: string;
  path: string;
  deleted_at: number;
}

/** Response from `keep.get()`. */
export interface KeepGetResponse {
  status: string;
  path: string;
  version: string;
  value: string;
  created_at: number;
  created_by: string;
}

/** Response from `keep.health()`. */
export interface KeepHealthResponse {
  status: string;
}

/** Response from `keep.list()`. */
export interface KeepListResponse {
  status: string;
  count: number;
  paths: unknown[];
}

/** Response from `keep.put()`. */
export interface KeepPutResponse {
  status: string;
  path: string;
  version: string;
}

/** Response from `keep.rotate()`. */
export interface KeepRotateResponse {
  status: string;
  path: string;
  version: string;
}

/** Response from `keep.versions()`. */
export interface KeepVersionsResponse {
  status: string;
  path: string;
  version_count: number;
  versions: unknown[];
  deleted: boolean;
}

