// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `scroll.ACK()`. */
export interface ScrollAckResponse {
  status: string;
}

/** Response from `scroll.APPEND()`. */
export interface ScrollAppendResponse {
  offset: number;
  status: string;
}

/** Response from `scroll.AUTH()`. */
export interface ScrollAuthResponse {
  status: string;
}

/** Response from `scroll.CLAIM()`. */
export interface ScrollClaimResponse {
  claimed: unknown[];
  status: string;
}

/** Response from `scroll.COMMAND LIST()`. */
export interface ScrollCommandListResponse {
  commands: unknown[];
}

/** Response from `scroll.CREATE_GROUP()`. */
export interface ScrollCreateGroupResponse {
  status: string;
}

/** Response from `scroll.DELETE_GROUP()`. */
export interface ScrollDeleteGroupResponse {
  status: string;
}

/** Response from `scroll.DELETE_LOG()`. */
export interface ScrollDeleteLogResponse {
  status: string;
}

/** Response from `scroll.GROUP_INFO()`. */
export interface ScrollGroupInfoResponse {
  created_at_ms: number;
  group: string;
  last_delivered_offset: number;
  log: string;
  members: unknown[];
  pending_count: number;
}

/** Response from `scroll.HEALTH()`. */
export interface ScrollHealthResponse {
  status: string;
}

/** Response from `scroll.HELLO()`. */
export interface ScrollHelloResponse {
  capabilities: unknown[];
  commands: unknown[];
  engine: string;
  protocol: string;
  version: string;
}

/** Response from `scroll.LOG_INFO()`. */
export interface ScrollLogInfoResponse {
  created_at_ms: number;
  entries_minted: number;
  groups: unknown[];
  latest_offset: unknown;
  log: string;
}

/** Response from `scroll.READ()`. */
export interface ScrollReadResponse {
  entries: unknown[];
  status: string;
}

/** Response from `scroll.READ_GROUP()`. */
export interface ScrollReadGroupResponse {
  entries: unknown[];
  status: string;
}

/** Response from `scroll.REPLAY()`. */
export interface ScrollReplayResponse {
  status: string;
}

/** Response from `scroll.TAIL()`. */
export interface ScrollTailResponse {
  entries: unknown[];
  status: string;
}

/** Response from `scroll.TRIM()`. */
export interface ScrollTrimResponse {
  deleted: number;
  status: string;
}

