// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `sentry.AUTH()`. */
export interface SentryAuthResponse {
  status: string;
}

/** Response from `sentry.COMMAND_LIST()`. */
export interface SentryCommandListResponse {
  commands: unknown[];
  status: string;
}

/** Response from `sentry.EVALUATE()`. */
export interface SentryEvaluateResponse {
  cache_until: number;
  decision: string;
  matched_policy: string;
  status: string;
  token: string;
}

/** Response from `sentry.HEALTH()`. */
export interface SentryHealthResponse {
  policy_count: number;
  status: string;
}

/** Response from `sentry.HELLO()`. */
export interface SentryHelloResponse {
  capabilities: unknown[];
  commands: unknown[];
  engine: string;
  protocol: string;
  version: string;
}

/** Response from `sentry.JWKS()`. */
export interface SentryJwksResponse {
  keys: unknown[];
}

/** Response from `sentry.KEY_INFO()`. */
export interface SentryKeyInfoResponse {
  active_kid: string;
  active_version: number;
  algorithm: string;
  decision_ttl_secs: number;
  drain_days: number;
  jwks_keys: number;
  rotation_days: number;
  status: string;
  total_versions: number;
}

/** Response from `sentry.KEY_ROTATE()`. */
export interface SentryKeyRotateResponse {
  key_version: number;
  previous_version: number;
  rotated: boolean;
  status: string;
}

/** Response from `sentry.POLICY_CREATE()`. */
export interface SentryPolicyCreateResponse {
  effect: string;
  name: string;
  priority: number;
  status: string;
  version: number;
}

/** Response from `sentry.POLICY_DELETE()`. */
export interface SentryPolicyDeleteResponse {
  status: string;
}

/** Response from `sentry.POLICY_GET()`. */
export interface SentryPolicyGetResponse {
  action: unknown;
  conditions: unknown;
  created_at: number;
  description: string;
  effect: string;
  name: string;
  principal: unknown;
  priority: number;
  resource: unknown;
  status: string;
  updated_at: number;
  version: number;
}

/** Response from `sentry.POLICY_HISTORY()`. */
export interface SentryPolicyHistoryResponse {
  count: number;
  name: string;
  status: string;
  versions: unknown[];
}

/** Response from `sentry.POLICY_LIST()`. */
export interface SentryPolicyListResponse {
  count: number;
  policies: unknown[];
  status: string;
}

/** Response from `sentry.POLICY_UPDATE()`. */
export interface SentryPolicyUpdateResponse {
  effect: string;
  name: string;
  priority: number;
  status: string;
  updated_at: number;
  version: number;
}

