// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `shroudb.AUTH()`. */
export interface ShroudbAuthResponse {
  actor: string;
}

/** Response from `shroudb.COMMAND LIST()`. */
export interface ShroudbCommandListResponse {
  commands: unknown[];
  count: number;
}

/** Response from `shroudb.CONFIG GET()`. */
export interface ShroudbConfigGetResponse {
  key: string;
  value: unknown;
}

/** Response from `shroudb.DELETE()`. */
export interface ShroudbDeleteResponse {
  version: number;
}

/** Response from `shroudb.GET()`. */
export interface ShroudbGetResponse {
  key: unknown;
  metadata: unknown;
  value: unknown;
  version: number;
}

/** Response from `shroudb.HEALTH()`. */
export interface ShroudbHealthResponse {
  message: string;
}

/** Response from `shroudb.LIST()`. */
export interface ShroudbListResponse {
  cursor: unknown;
  keys: unknown[];
}

/** Response from `shroudb.NAMESPACE INFO()`. */
export interface ShroudbNamespaceInfoResponse {
  created_at: number;
  key_count: number;
  name: string;
}

/** Response from `shroudb.NAMESPACE LIST()`. */
export interface ShroudbNamespaceListResponse {
  cursor: unknown;
  namespaces: unknown[];
}

/** Response from `shroudb.NAMESPACE VALIDATE()`. */
export interface ShroudbNamespaceValidateResponse {
  count: number;
  reports: unknown[];
}

/** Response from `shroudb.PING()`. */
export interface ShroudbPingResponse {
  message: string;
}

/** Response from `shroudb.PUT()`. */
export interface ShroudbPutResponse {
  version: number;
}

/** Response from `shroudb.VERSIONS()`. */
export interface ShroudbVersionsResponse {
  versions: unknown[];
}

