// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `sigil.AUTH()`. */
export interface SigilAuthResponse {
  status: string;
}

/** Response from `sigil.CREDENTIAL_CHANGE()`. */
export interface SigilCredentialChangeResponse {
  status: string;
}

/** Response from `sigil.CREDENTIAL_IMPORT()`. */
export interface SigilCredentialImportResponse {
  algorithm: string;
  status: string;
}

/** Response from `sigil.CREDENTIAL_RESET()`. */
export interface SigilCredentialResetResponse {
  status: string;
}

/** Response from `sigil.ENVELOPE_CREATE()`. */
export interface SigilEnvelopeCreateResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
}

/** Response from `sigil.ENVELOPE_DELETE()`. */
export interface SigilEnvelopeDeleteResponse {
  status: string;
}

/** Response from `sigil.ENVELOPE_GET()`. */
export interface SigilEnvelopeGetResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  updated_at: number;
}

/** Response from `sigil.ENVELOPE_IMPORT()`. */
export interface SigilEnvelopeImportResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
}

/** Response from `sigil.ENVELOPE_LOOKUP()`. */
export interface SigilEnvelopeLookupResponse {
  entity_id: string;
  status: string;
}

/** Response from `sigil.ENVELOPE_UPDATE()`. */
export interface SigilEnvelopeUpdateResponse {
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
  updated_at: number;
}

/** Response from `sigil.ENVELOPE_VERIFY()`. */
export interface SigilEnvelopeVerifyResponse {
  status: string;
  valid: boolean;
}

/** Response from `sigil.HEALTH()`. */
export interface SigilHealthResponse {
  status: string;
}

/** Response from `sigil.PASSWORD_CHANGE()`. */
export interface SigilPasswordChangeResponse {
  status: string;
}

/** Response from `sigil.PASSWORD_IMPORT()`. */
export interface SigilPasswordImportResponse {
  algorithm: string;
  status: string;
}

/** Response from `sigil.PASSWORD_RESET()`. */
export interface SigilPasswordResetResponse {
  status: string;
}

/** Response from `sigil.SCHEMA_ALTER()`. */
export interface SigilSchemaAlterResponse {
  fields: number;
  name: string;
  status: string;
  version: number;
}

/** Response from `sigil.SCHEMA_REGISTER()`. */
export interface SigilSchemaRegisterResponse {
  status: string;
  version: number;
}

/** Response from `sigil.SESSION_CREATE()`. */
export interface SigilSessionCreateResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  status: string;
}

/** Response from `sigil.SESSION_LOGIN()`. */
export interface SigilSessionLoginResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  status: string;
}

/** Response from `sigil.SESSION_REFRESH()`. */
export interface SigilSessionRefreshResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  status: string;
}

/** Response from `sigil.SESSION_REVOKE()`. */
export interface SigilSessionRevokeResponse {
  status: string;
}

/** Response from `sigil.SESSION_REVOKE_ALL()`. */
export interface SigilSessionRevokeAllResponse {
  revoked: number;
  status: string;
}

/** Response from `sigil.USER_CREATE()`. */
export interface SigilUserCreateResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
}

/** Response from `sigil.USER_DELETE()`. */
export interface SigilUserDeleteResponse {
  status: string;
}

/** Response from `sigil.USER_GET()`. */
export interface SigilUserGetResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  updated_at: number;
}

/** Response from `sigil.USER_IMPORT()`. */
export interface SigilUserImportResponse {
  created_at: number;
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
}

/** Response from `sigil.USER_LOOKUP()`. */
export interface SigilUserLookupResponse {
  entity_id: string;
  status: string;
}

/** Response from `sigil.USER_UPDATE()`. */
export interface SigilUserUpdateResponse {
  entity_id: string;
  fields: Record<string, unknown>;
  status: string;
  updated_at: number;
}

/** Response from `sigil.USER_VERIFY()`. */
export interface SigilUserVerifyResponse {
  status: string;
  valid: boolean;
}

