// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `sigil.CREDENTIAL_CHANGE()`. */
export interface SigilCredentialChangeResponse {
  status: string;
}

/** Response from `sigil.CREDENTIAL_IMPORT()`. */
export interface SigilCredentialImportResponse {
  algorithm: string;
}

/** Response from `sigil.CREDENTIAL_RESET()`. */
export interface SigilCredentialResetResponse {
  status: string;
}

/** Response from `sigil.ENVELOPE_CREATE()`. */
export interface SigilEnvelopeCreateResponse {
  created_at: number;
  fields: Record<string, unknown>;
  id: string;
}

/** Response from `sigil.ENVELOPE_DELETE()`. */
export interface SigilEnvelopeDeleteResponse {
  status: string;
}

/** Response from `sigil.ENVELOPE_GET()`. */
export interface SigilEnvelopeGetResponse {
  created_at: number;
  fields: Record<string, unknown>;
  id: string;
  updated_at: number;
}

/** Response from `sigil.ENVELOPE_IMPORT()`. */
export interface SigilEnvelopeImportResponse {
  created_at: number;
  fields: Record<string, unknown>;
  id: string;
}

/** Response from `sigil.ENVELOPE_LOOKUP()`. */
export interface SigilEnvelopeLookupResponse {
  created_at: number;
  fields: Record<string, unknown>;
  id: string;
  updated_at: number;
}

/** Response from `sigil.ENVELOPE_UPDATE()`. */
export interface SigilEnvelopeUpdateResponse {
  fields: Record<string, unknown>;
  id: string;
  updated_at: number;
}

/** Response from `sigil.ENVELOPE_VERIFY()`. */
export interface SigilEnvelopeVerifyResponse {
  valid: boolean;
}

/** Response from `sigil.HEALTH()`. */
export interface SigilHealthResponse {
  status: string;
}

/** Response from `sigil.JWKS()`. */
export interface SigilJwksResponse {
  keys: unknown[];
}

/** Response from `sigil.PASSWORD_CHANGE()`. */
export interface SigilPasswordChangeResponse {
  status: string;
}

/** Response from `sigil.PASSWORD_IMPORT()`. */
export interface SigilPasswordImportResponse {
  algorithm: string;
}

/** Response from `sigil.PASSWORD_RESET()`. */
export interface SigilPasswordResetResponse {
  status: string;
}

/** Response from `sigil.SCHEMA_ALTER()`. */
export interface SigilSchemaAlterResponse {
  fields: number;
  name: string;
  version: number;
}

/** Response from `sigil.SCHEMA_GET()`. */
export interface SigilSchemaGetResponse {
  schema: unknown;
}

/** Response from `sigil.SCHEMA_LIST()`. */
export interface SigilSchemaListResponse {
  names: unknown[];
}

/** Response from `sigil.SCHEMA_REGISTER()`. */
export interface SigilSchemaRegisterResponse {
  version: number;
}

/** Response from `sigil.SESSION_CREATE()`. */
export interface SigilSessionCreateResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
}

/** Response from `sigil.SESSION_LIST()`. */
export interface SigilSessionListResponse {
  sessions: unknown[];
}

/** Response from `sigil.SESSION_REFRESH()`. */
export interface SigilSessionRefreshResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
}

/** Response from `sigil.SESSION_REVOKE()`. */
export interface SigilSessionRevokeResponse {
  status: string;
}

/** Response from `sigil.SESSION_REVOKE_ALL()`. */
export interface SigilSessionRevokeAllResponse {
  revoked: number;
}

/** Response from `sigil.USER_CREATE()`. */
export interface SigilUserCreateResponse {
  created_at: number;
  fields: Record<string, unknown>;
  user_id: string;
}

/** Response from `sigil.USER_DELETE()`. */
export interface SigilUserDeleteResponse {
  status: string;
}

/** Response from `sigil.USER_GET()`. */
export interface SigilUserGetResponse {
  created_at: number;
  fields: Record<string, unknown>;
  updated_at: number;
  user_id: string;
}

/** Response from `sigil.USER_IMPORT()`. */
export interface SigilUserImportResponse {
  created_at: number;
  fields: Record<string, unknown>;
  user_id: string;
}

/** Response from `sigil.USER_UPDATE()`. */
export interface SigilUserUpdateResponse {
  fields: Record<string, unknown>;
  updated_at: number;
  user_id: string;
}

/** Response from `sigil.USER_VERIFY()`. */
export interface SigilUserVerifyResponse {
  valid: boolean;
}

