// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `stash.fingerprint()`. */
export interface StashFingerprintResponse {
  created_at: number;
  s3_key: string;
  status: string;
  viewer_id: string;
}

/** Response from `stash.inspect()`. */
export interface StashInspectResponse {
  blob_status: string;
  client_encrypted: boolean;
  content_type: string;
  created_at: number;
  encrypted_size: number;
  id: string;
  key_version: number;
  keyring: string;
  plaintext_size: number;
  status: string;
  updated_at: number;
  viewer_count: number;
}

/** Response from `stash.list()`. */
export interface StashListResponse {
  blobs: unknown[];
  count: number;
  status: string;
  tenant: string;
}

/** Response from `stash.revoke()`. */
export interface StashRevokeResponse {
  id: string;
  revoke_mode: string;
  status: string;
}

/** Response from `stash.rewrap()`. */
export interface StashRewrapResponse {
  id: string;
  key_version: number;
  status: string;
  updated_at: number;
}

/** Response from `stash.store()`. */
export interface StashStoreResponse {
  client_encrypted: boolean;
  content_hash: unknown;
  deduplicated: boolean;
  encrypted_size: number;
  id: string;
  key_version: number;
  keyring: string;
  plaintext_size: number;
  s3_key: string;
  status: string;
}

/** Response from `stash.trace()`. */
export interface StashTraceResponse {
  blob_status: string;
  id: string;
  status: string;
  viewer_count: number;
  viewers: unknown[];
}

