// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `stash.inspect()`. */
export interface StashInspectResponse {
  blob_status: string;
  client_encrypted: boolean;
  content_type: string;
  created_at: number;
  encrypted_size: number;
  id: string;
  key_version: number;
  keyring: string;
  plaintext_size: number;
  status: string;
  updated_at: number;
  viewer_count: number;
}

/** Response from `stash.revoke()`. */
export interface StashRevokeResponse {
  id: string;
  revoke_mode: string;
  status: string;
}

/** Response from `stash.store()`. */
export interface StashStoreResponse {
  client_encrypted: boolean;
  encrypted_size: number;
  id: string;
  key_version: number;
  keyring: string;
  plaintext_size: number;
  s3_key: string;
  status: string;
}

