// Auto-generated by shroudb-codegen. Do not edit.

/** Response from `veil.AUTH()`. */
export interface VeilAuthResponse {
  status: unknown;
}

/** Response from `veil.COMMAND_LIST()`. */
export interface VeilCommandListResponse {
  count: unknown;
  commands: unknown;
}

/** Response from `veil.DELETE()`. */
export interface VeilDeleteResponse {
  status: unknown;
  id: unknown;
}

/** Response from `veil.HEALTH()`. */
export interface VeilHealthResponse {
  status: unknown;
}

/** Response from `veil.HELLO()`. */
export interface VeilHelloResponse {
  engine: unknown;
  version: unknown;
  protocol: unknown;
  commands: unknown;
  capabilities: unknown;
}

/** Response from `veil.INDEX_CREATE()`. */
export interface VeilIndexCreateResponse {
  status: unknown;
  index: unknown;
  created_at: unknown;
  tokenizer_version: unknown;
}

/** Response from `veil.INDEX_DESTROY()`. */
export interface VeilIndexDestroyResponse {
  status: unknown;
  index: unknown;
  deleted_entries: unknown;
}

/** Response from `veil.INDEX_INFO()`. */
export interface VeilIndexInfoResponse {
  index: unknown;
  created_at: unknown;
  entry_count: unknown;
  tokenizer_version: unknown;
}

/** Response from `veil.INDEX_LIST()`. */
export interface VeilIndexListResponse {
  items: string;
  type: unknown[];
}

/** Response from `veil.INDEX_RECONCILE()`. */
export interface VeilIndexReconcileResponse {
  status: unknown;
  index: unknown;
  orphans_removed: unknown;
}

/** Response from `veil.INDEX_REINDEX()`. */
export interface VeilIndexReindexResponse {
  status: unknown;
  index: unknown;
  tokenizer_version: unknown;
  entries_cleared: unknown;
}

/** Response from `veil.INDEX_ROTATE()`. */
export interface VeilIndexRotateResponse {
  status: unknown;
  index: unknown;
  rotated_at: unknown;
  entry_count: unknown;
}

/** Response from `veil.PING()`. */
export interface VeilPingResponse {
  type: string;
  value: unknown;
}

/** Response from `veil.PUT()`. */
export interface VeilPutResponse {
  status: unknown;
  id: unknown;
  version: unknown;
}

/** Response from `veil.SEARCH()`. */
export interface VeilSearchResponse {
  status: unknown;
  scanned: unknown;
  matched: unknown;
  results: unknown;
}

/** Response from `veil.TOKENIZE()`. */
export interface VeilTokenizeResponse {
  status: unknown;
  words: unknown;
  trigrams: unknown;
  tokens: unknown;
}

