// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport, CommandResult } from "./interface.js";
import { ShrouDBError } from "../errors.js";

/**
 * HTTP transport for Moat gateway connections.
 *
 * Commands are POSTed to `/v1/{engine}` as `{ "args": [...] }`.
 */
export class HttpTransport implements Transport {
  private buffered: Map<string, string[][]> = new Map();

  constructor(
    private baseUrl: string,
    private token?: string,
    private prefixes: Map<string, string> = new Map(),
  ) {
    // Strip trailing slash.
    if (this.baseUrl.endsWith("/")) {
      this.baseUrl = this.baseUrl.slice(0, -1);
    }
  }

  async executeMany(engine: string, argsList: string[][]): Promise<CommandResult[]> {
    // HTTP has no pipelining; fall back to sequential requests, returning in order.
    const results: CommandResult[] = [];
    for (const args of argsList) {
      results.push(await this.execute(engine, args));
    }
    return results;
  }

  async executePipeline(
    _engine: string,
    _commands: string[][],
    _requestId?: string,
  ): Promise<CommandResult[]> {
    throw ShrouDBError._fromServer(
      "NOT_SUPPORTED",
      "PIPELINE is a RESP3-only command; use Resp3Transport or MoatResp3Transport",
    );
  }

  async execute(engine: string, args: string[]): Promise<CommandResult> {
    const prefix = this.prefixes.get(engine) ?? `/v1/${engine}`;
    const url = `${this.baseUrl}${prefix}`;
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (this.token) {
      headers["Authorization"] = `Bearer ${this.token}`;
    }

    const resp = await fetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify({ args }),
    });

    if (!resp.ok) {
      const text = await resp.text();
      let code = "INTERNAL";
      let detail = text;
      try {
        const json = JSON.parse(text);
        if (json.error) {
          const parts = json.error.split(" ", 2);
          code = parts[0];
          detail = parts[1] ?? json.error;
        }
      } catch { /* raw text */ }
      throw ShrouDBError._fromServer(code, detail);
    }

    return resp.json() as Promise<CommandResult>;
  }

  buffer(engine: string, args: string[]): void {
    const list = this.buffered.get(engine) ?? [];
    list.push(args);
    this.buffered.set(engine, list);
  }

  async flush(engine: string): Promise<CommandResult[]> {
    const list = this.buffered.get(engine) ?? [];
    this.buffered.delete(engine);
    const results: CommandResult[] = [];
    for (const args of list) {
      results.push(await this.execute(engine, args));
    }
    return results;
  }

  async close(): Promise<void> {
    // HTTP is stateless — nothing to close.
  }
}
