// Auto-generated by shroudb-codegen. Do not edit.

/** Result of a command execution. */
export type CommandResult = Record<string, unknown>;

/**
 * Transport abstraction for ShrouDB engine communication.
 *
 * Implementations handle the wire format (RESP3 or HTTP) and connection
 * lifecycle. Engine namespace classes use this interface exclusively.
 */
export interface Transport {
  /** Execute a command and return the parsed response. */
  execute(engine: string, args: string[]): Promise<CommandResult>;

  /** Send a command without waiting for a response (pipeline buffering). */
  buffer(engine: string, args: string[]): void;

  /** Flush buffered commands and return all responses. */
  flush(engine: string): Promise<CommandResult[]>;

  /** Close all connections. */
  close(): Promise<void>;
}
