// Auto-generated by shroudb-codegen. Do not edit.

import { createConnection, Socket } from "net";
import { connect as tlsConnect, TLSSocket } from "tls";
import type { Transport, CommandResult } from "./interface.js";
import { ShrouDBError } from "../errors.js";

type WireValue = string | number | null | WireValue[] | { [key: string]: WireValue };

/** Parse a RESP3 URI into connection parameters. */
function parseUri(uri: string): { host: string; port: number; tls: boolean; token?: string; keyspace?: string } {
  const match = uri.match(/^([\w-]+)(\+tls)?:\/\/(?:([^@]+)@)?([^:/]+)(?::(\d+))?(?:\/(.+))?$/);
  if (!match) throw new Error(`Invalid ShrouDB URI: ${uri}`);
  return {
    host: match[4],
    port: match[5] ? parseInt(match[5], 10) : 6399,
    tls: match[2] === "+tls",
    token: match[3] || undefined,
    keyspace: match[6] || undefined,
  };
}

class Connection {
  private buffer = "";
  private resolveQueue: Array<(value: WireValue) => void> = [];
  private rejectQueue: Array<(reason: Error) => void> = [];
  private pendingBuffered: string[] = [];

  private constructor(private socket: Socket | TLSSocket) {
    socket.setEncoding("utf-8");
    socket.on("data", (chunk: string) => {
      this.buffer += chunk;
      this.drain();
    });
    socket.on("error", (err: Error) => {
      for (const reject of this.rejectQueue) reject(err);
      this.resolveQueue = [];
      this.rejectQueue = [];
    });
  }

  static async open(host: string, port: number, tls: boolean): Promise<Connection> {
    return new Promise((resolve, reject) => {
      if (tls) {
        const socket = tlsConnect({ host, port }, () => resolve(new Connection(socket)));
        socket.on("error", reject);
      } else {
        const socket = createConnection({ host, port }, () => resolve(new Connection(socket)));
        socket.on("error", reject);
      }
    });
  }

  async execute(...args: string[]): Promise<WireValue> {
    this.sendRaw(args);
    return new Promise<WireValue>((resolve, reject) => {
      this.resolveQueue.push(resolve);
      this.rejectQueue.push(reject);
      this.drain();
    });
  }

  bufferCommand(args: string[]): void {
    this.sendRaw(args);
    this.pendingBuffered.push("queued");
  }

  async flushBuffered(): Promise<WireValue[]> {
    const count = this.pendingBuffered.length;
    this.pendingBuffered = [];
    const results: WireValue[] = [];
    for (let i = 0; i < count; i++) {
      results.push(await new Promise<WireValue>((resolve, reject) => {
        this.resolveQueue.push(resolve);
        this.rejectQueue.push(reject);
        this.drain();
      }));
    }
    return results;
  }

  close(): void {
    this.socket.end();
  }

  private sendRaw(args: string[]): void {
    let cmd = `*${args.length}\r\n`;
    for (const arg of args) {
      const bytes = Buffer.byteLength(arg, "utf-8");
      cmd += `$${bytes}\r\n${arg}\r\n`;
    }
    this.socket.write(cmd);
  }

  private drain(): void {
    while (this.resolveQueue.length > 0) {
      const result = this.parseFrame(this.buffer);
      if (result === undefined) break;
      const resolve = this.resolveQueue.shift()!;
      this.rejectQueue.shift();
      resolve(result.value);
    }
  }

  private parseFrame(buf: string): { value: WireValue; rest: string } | undefined {
    const nlIdx = buf.indexOf("\r\n");
    if (nlIdx < 0) return undefined;

    const tag = buf[0];
    const payload = buf.substring(1, nlIdx);
    const after = buf.substring(nlIdx + 2);

    switch (tag) {
      case "+":
        this.buffer = after;
        return { value: payload, rest: after };
      case "-": {
        const spaceIdx = payload.indexOf(" ");
        let code = spaceIdx >= 0 ? payload.substring(0, spaceIdx) : payload;
        const detail = spaceIdx >= 0 ? payload.substring(spaceIdx + 1) : "";
        // Engines send "ERR {message}" — infer a structured code from the message.
        if (code === "ERR") code = inferErrorCode(detail);
        this.buffer = after;
        const reject = this.rejectQueue.shift();
        this.resolveQueue.shift();
        if (reject) reject(ShrouDBError._fromServer(code, detail));
        return undefined;
      }
      case ":":
        this.buffer = after;
        return { value: parseInt(payload, 10), rest: after };
      case "$": {
        const len = parseInt(payload, 10);
        if (len < 0) {
          this.buffer = after;
          return { value: null, rest: after };
        }
        if (after.length < len + 2) return undefined;
        const data = after.substring(0, len);
        const rest = after.substring(len + 2);
        this.buffer = rest;
        return { value: data, rest };
      }
      case "*": {
        const count = parseInt(payload, 10);
        if (count < 0) {
          this.buffer = after;
          return { value: null, rest: after };
        }
        let remaining = after;
        const items: WireValue[] = [];
        for (let i = 0; i < count; i++) {
          const sub = this.parseFrame(remaining);
          if (sub === undefined) return undefined;
          items.push(sub.value);
          remaining = sub.rest;
        }
        this.buffer = remaining;
        return { value: items, rest: remaining };
      }
      case "%": {
        const count = parseInt(payload, 10);
        let remaining = after;
        const map: Record<string, WireValue> = {};
        for (let i = 0; i < count; i++) {
          const keyFrame = this.parseFrame(remaining);
          if (keyFrame === undefined) return undefined;
          remaining = keyFrame.rest;
          const valFrame = this.parseFrame(remaining);
          if (valFrame === undefined) return undefined;
          remaining = valFrame.rest;
          map[String(keyFrame.value)] = valFrame.value;
        }
        this.buffer = remaining;
        return { value: map, rest: remaining };
      }
      default:
        this.buffer = after;
        return { value: payload, rest: after };
    }
  }
}

/** Connection pool for a single RESP3 endpoint. */
class ConnectionPool {
  private idle: Connection[] = [];
  private active = 0;
  private waiters: Array<(conn: Connection) => void> = [];

  constructor(
    private host: string,
    private port: number,
    private tls: boolean,
    private maxConnections: number = 10,
    private token?: string,
  ) {}

  async acquire(): Promise<Connection> {
    const conn = this.idle.pop();
    if (conn) {
      this.active++;
      return conn;
    }
    if (this.active < this.maxConnections) {
      this.active++;
      const newConn = await Connection.open(this.host, this.port, this.tls);
      if (this.token) {
        await newConn.execute("AUTH", this.token);
      }
      return newConn;
    }
    return new Promise((resolve) => this.waiters.push(resolve));
  }

  release(conn: Connection): void {
    this.active--;
    const waiter = this.waiters.shift();
    if (waiter) {
      this.active++;
      waiter(conn);
    } else {
      this.idle.push(conn);
    }
  }

  async close(): Promise<void> {
    for (const conn of this.idle) conn.close();
    this.idle = [];
  }
}

/**
 * RESP3 transport for direct engine connections.
 *
 * Each engine gets its own connection pool. Commands are sent as RESP3
 * arrays of bulk strings.
 */
export class Resp3Transport implements Transport {
  private pool: ConnectionPool;
  private bufferedArgs: string[][] = [];

  constructor(uri: string) {
    const parsed = parseUri(uri);
    this.pool = new ConnectionPool(
      parsed.host,
      parsed.port,
      parsed.tls,
      10,
      parsed.token,
    );
  }

  async execute(_engine: string, args: string[]): Promise<CommandResult> {
    const conn = await this.pool.acquire();
    try {
      const raw = await conn.execute(...args);
      return parseResponse(raw);
    } finally {
      this.pool.release(conn);
    }
  }

  buffer(_engine: string, args: string[]): void {
    this.bufferedArgs.push(args);
  }

  async flush(_engine: string): Promise<CommandResult[]> {
    const conn = await this.pool.acquire();
    try {
      for (const args of this.bufferedArgs) {
        conn.bufferCommand(args);
      }
      const raw = await conn.flushBuffered();
      this.bufferedArgs = [];
      return raw.map(parseResponse);
    } finally {
      this.pool.release(conn);
    }
  }

  async close(): Promise<void> {
    await this.pool.close();
  }
}

/**
 * RESP3 transport for Moat gateway connections.
 *
 * Commands are prefixed with the engine name before sending.
 */
export class MoatResp3Transport implements Transport {
  private pool: ConnectionPool;
  private buffered: Map<string, string[][]> = new Map();

  constructor(uri: string) {
    const parsed = parseUri(uri);
    this.pool = new ConnectionPool(
      parsed.host,
      parsed.port,
      parsed.tls,
      10,
      parsed.token,
    );
  }

  async execute(engine: string, args: string[]): Promise<CommandResult> {
    const prefixed = [engine.toUpperCase(), ...args];
    const conn = await this.pool.acquire();
    try {
      const raw = await conn.execute(...prefixed);
      return parseResponse(raw);
    } finally {
      this.pool.release(conn);
    }
  }

  buffer(engine: string, args: string[]): void {
    const prefixed = [engine.toUpperCase(), ...args];
    const list = this.buffered.get(engine) ?? [];
    list.push(prefixed);
    this.buffered.set(engine, list);
  }

  async flush(_engine: string): Promise<CommandResult[]> {
    const conn = await this.pool.acquire();
    try {
      const all: string[][] = [];
      for (const list of this.buffered.values()) {
        all.push(...list);
      }
      for (const args of all) {
        conn.bufferCommand(args);
      }
      const raw = await conn.flushBuffered();
      this.buffered.clear();
      return raw.map(parseResponse);
    } finally {
      this.pool.release(conn);
    }
  }

  async close(): Promise<void> {
    await this.pool.close();
  }
}

function parseResponse(raw: WireValue): CommandResult {
  if (raw === null) return {};
  if (typeof raw === "string") {
    try {
      const parsed = JSON.parse(raw);
      if (typeof parsed === "object" && parsed !== null) return parsed;
    } catch { /* not JSON */ }
    return { data: raw };
  }
  if (typeof raw === "number") return { value: raw };
  if (typeof raw === "object" && !Array.isArray(raw)) return raw as CommandResult;
  return { data: raw };
}

/**
 * Infer a structured error code from an engine error message.
 *
 * Engines send generic `ERR {message}` errors. This function maps known
 * message patterns back to the structured codes defined in protocol.toml.
 */
function inferErrorCode(message: string): string {
  const m = message.toLowerCase();
  if (m.includes("not found")) return "NOTFOUND";
  if (m.includes("already exists")) return "EXISTS";
  if (m.includes("is deleted") || m.includes("soft-revoked")) return "DELETED";
  if (m.includes("access denied") || m.includes("policy denied")) return "DENIED";
  if (m.includes("not authenticated")) return "NOT_AUTHENTICATED";
  if (m.includes("verification failed")) return "VERIFICATION_FAILED";
  if (m.includes("account locked")) return "ACCOUNT_LOCKED";
  if (m.includes("invalid token") || m.includes("token reuse")) return "INVALID_TOKEN";
  if (m.includes("invalid argument") || m.includes("invalid path") || m.includes("bad argument")) return "BADARG";
  if (m.includes("unknown command")) return "BADARG";
  if (m.includes("schema validation")) return "SCHEMA_VALIDATION";
  if (m.includes("missing") && m.includes("field")) return "MISSING_FIELD";
  if (m.includes("invalid field")) return "INVALID_FIELD";
  if (m.includes("capability") || m.includes("unavailable")) return "CAPABILITY_MISSING";
  if (m.includes("retired")) return "RETIRED";
  if (m.includes("disabled")) return "DISABLED";
  if (m.includes("algorithm mismatch") || m.includes("wrong type")) return "WRONGTYPE";
  if (m.includes("shredded") || m.includes("crypto-shred")) return "SHREDDED";
  if (m.includes("revoked")) return "REVOKED";
  if (m.includes("object store") || m.includes("s3")) return "OBJECT_STORE";
  if (m.includes("encryption failed") || m.includes("decryption failed")) return "CRYPTO";
  if (m.includes("store error")) return "INTERNAL";
  return "ERR";
}
