// Auto-generated by shroudb-codegen. Do not edit.

import type { Transport } from './transport/interface.js';
import { HttpTransport } from './transport/http.js';
import { Resp3Transport, MoatResp3Transport } from './transport/resp3.js';
import { ShroudbNamespace } from './engines/shroudb.js';
import { CipherNamespace } from './engines/cipher.js';
import { SigilNamespace } from './engines/sigil.js';
import { VeilNamespace } from './engines/veil.js';
import { SentryNamespace } from './engines/sentry.js';
import { ForgeNamespace } from './engines/forge.js';
import { KeepNamespace } from './engines/keep.js';
import { CourierNamespace } from './engines/courier.js';
import { ChronicleNamespace } from './engines/chronicle.js';

export interface ShrouDBOptions {
  /**
   * Moat gateway URL. When set, engines without a dedicated URI are
   * routed through this gateway.
   *
   * HTTP: `https://moat.example.com`
   * RESP3: `shroudb-moat://token@host:8201`
   */
  moat?: string;

  /** Bearer token for Moat HTTP authentication. */
  token?: string;

  /** Direct shroudb URI (overrides Moat for this engine). */
  shroudb?: string;
  /** Direct cipher URI (overrides Moat for this engine). */
  cipher?: string;
  /** Direct sigil URI (overrides Moat for this engine). */
  sigil?: string;
  /** Direct veil URI (overrides Moat for this engine). */
  veil?: string;
  /** Direct sentry URI (overrides Moat for this engine). */
  sentry?: string;
  /** Direct forge URI (overrides Moat for this engine). */
  forge?: string;
  /** Direct keep URI (overrides Moat for this engine). */
  keep?: string;
  /** Direct courier URI (overrides Moat for this engine). */
  courier?: string;
  /** Direct chronicle URI (overrides Moat for this engine). */
  chronicle?: string;
}

/**
 * ShrouDB unified client.
 *
 * Provides namespaced access to all ShrouDB engines. Each engine is
 * accessible as a property (e.g., `db.cipher.encrypt(...)`).
 *
 * Supply a `moat` URL to route all engines through a Moat gateway,
 * or individual engine URIs for direct connections.
 */
export class ShrouDB {
  public readonly shroudb: ShroudbNamespace;
  public readonly cipher: CipherNamespace;
  public readonly sigil: SigilNamespace;
  public readonly veil: VeilNamespace;
  public readonly sentry: SentryNamespace;
  public readonly forge: ForgeNamespace;
  public readonly keep: KeepNamespace;
  public readonly courier: CourierNamespace;
  public readonly chronicle: ChronicleNamespace;

  private transports: Transport[] = [];

  constructor(options: ShrouDBOptions) {
    // Resolve the default transport from the Moat URI.
    let defaultTransport: Transport | undefined;
    if (options.moat) {
      if (options.moat.startsWith('http://') || options.moat.startsWith('https://')) {
        const prefixes = new Map<string, string>();
        prefixes.set("shroudb", "/v1/shroudb");
        prefixes.set("cipher", "/v1/cipher");
        prefixes.set("sigil", "/v1/sigil");
        prefixes.set("veil", "/v1/veil");
        prefixes.set("sentry", "/v1/sentry");
        prefixes.set("forge", "/v1/forge");
        prefixes.set("keep", "/v1/keep");
        prefixes.set("courier", "/v1/courier");
        prefixes.set("chronicle", "/v1/chronicle");
        defaultTransport = new HttpTransport(options.moat, options.token, prefixes);
      } else {
        defaultTransport = new MoatResp3Transport(options.moat);
      }
      this.transports.push(defaultTransport);
    }

    if (options.shroudb) {
      const t = new Resp3Transport(options.shroudb);
      this.transports.push(t);
      this.shroudb = new ShroudbNamespace(t, "shroudb");
    } else if (defaultTransport) {
      this.shroudb = new ShroudbNamespace(defaultTransport, "shroudb");
    } else {
      this.shroudb = new ShroudbNamespace({ execute: () => { throw new Error('No transport configured for shroudb. Provide a moat URL or shroudb URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "shroudb");
    }

    if (options.cipher) {
      const t = new Resp3Transport(options.cipher);
      this.transports.push(t);
      this.cipher = new CipherNamespace(t, "cipher");
    } else if (defaultTransport) {
      this.cipher = new CipherNamespace(defaultTransport, "cipher");
    } else {
      this.cipher = new CipherNamespace({ execute: () => { throw new Error('No transport configured for cipher. Provide a moat URL or cipher URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "cipher");
    }

    if (options.sigil) {
      const t = new Resp3Transport(options.sigil);
      this.transports.push(t);
      this.sigil = new SigilNamespace(t, "sigil");
    } else if (defaultTransport) {
      this.sigil = new SigilNamespace(defaultTransport, "sigil");
    } else {
      this.sigil = new SigilNamespace({ execute: () => { throw new Error('No transport configured for sigil. Provide a moat URL or sigil URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "sigil");
    }

    if (options.veil) {
      const t = new Resp3Transport(options.veil);
      this.transports.push(t);
      this.veil = new VeilNamespace(t, "veil");
    } else if (defaultTransport) {
      this.veil = new VeilNamespace(defaultTransport, "veil");
    } else {
      this.veil = new VeilNamespace({ execute: () => { throw new Error('No transport configured for veil. Provide a moat URL or veil URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "veil");
    }

    if (options.sentry) {
      const t = new Resp3Transport(options.sentry);
      this.transports.push(t);
      this.sentry = new SentryNamespace(t, "sentry");
    } else if (defaultTransport) {
      this.sentry = new SentryNamespace(defaultTransport, "sentry");
    } else {
      this.sentry = new SentryNamespace({ execute: () => { throw new Error('No transport configured for sentry. Provide a moat URL or sentry URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "sentry");
    }

    if (options.forge) {
      const t = new Resp3Transport(options.forge);
      this.transports.push(t);
      this.forge = new ForgeNamespace(t, "forge");
    } else if (defaultTransport) {
      this.forge = new ForgeNamespace(defaultTransport, "forge");
    } else {
      this.forge = new ForgeNamespace({ execute: () => { throw new Error('No transport configured for forge. Provide a moat URL or forge URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "forge");
    }

    if (options.keep) {
      const t = new Resp3Transport(options.keep);
      this.transports.push(t);
      this.keep = new KeepNamespace(t, "keep");
    } else if (defaultTransport) {
      this.keep = new KeepNamespace(defaultTransport, "keep");
    } else {
      this.keep = new KeepNamespace({ execute: () => { throw new Error('No transport configured for keep. Provide a moat URL or keep URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "keep");
    }

    if (options.courier) {
      const t = new Resp3Transport(options.courier);
      this.transports.push(t);
      this.courier = new CourierNamespace(t, "courier");
    } else if (defaultTransport) {
      this.courier = new CourierNamespace(defaultTransport, "courier");
    } else {
      this.courier = new CourierNamespace({ execute: () => { throw new Error('No transport configured for courier. Provide a moat URL or courier URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "courier");
    }

    if (options.chronicle) {
      const t = new Resp3Transport(options.chronicle);
      this.transports.push(t);
      this.chronicle = new ChronicleNamespace(t, "chronicle");
    } else if (defaultTransport) {
      this.chronicle = new ChronicleNamespace(defaultTransport, "chronicle");
    } else {
      this.chronicle = new ChronicleNamespace({ execute: () => { throw new Error('No transport configured for chronicle. Provide a moat URL or chronicle URI.'); }, buffer: () => {}, flush: async () => [], close: async () => {} }, "chronicle");
    }

  }

  /** Close all connections and release resources. */
  async close(): Promise<void> {
    await Promise.all(this.transports.map(t => t.close()));
  }
}
