// Auto-generated by shroudb-codegen. Do not edit.

/** Known ShrouDB error codes. */
export const ErrorCode = {
  /** Account locked after too many failed attempts. Only emitted for credential fields whose CredentialPolicy carries a non-null LockoutPolicy. */
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  /** Delivery adapter failure */
  ADAPTER: "ADAPTER",
  /** Authentication required */
  AUTH_REQUIRED: "AUTH_REQUIRED",
  /** Missing or invalid argument */
  BADARG: "BADARG",
  /** Missing or malformed command argument */
  BAD_ARG: "BAD_ARG",
  /** Required engine capability not available (e.g., Cipher for PII fields) */
  CAPABILITY_MISSING: "CAPABILITY_MISSING",
  /** Cipher engine not available for envelope encryption */
  CIPHER_UNAVAILABLE: "CIPHER_UNAVAILABLE",
  /** Cannot fingerprint a client-encrypted blob (client manages encryption) */
  CLIENT_ENCRYPTED: "CLIENT_ENCRYPTED",
  /** Encryption or decryption failed */
  CRYPTO: "CRYPTO",
  /** Cipher decryption failed */
  DECRYPT: "DECRYPT",
  /** Secret has been soft-deleted */
  DELETED: "DELETED",
  /** Authentication required or insufficient permissions */
  DENIED: "DENIED",
  /** Keyring is disabled */
  DISABLED: "DISABLED",
  /** Viewer already has a fingerprinted copy of this blob */
  DUPLICATE_VIEWER: "DUPLICATE_VIEWER",
  /** Encryption or decryption failed */
  ENCRYPTION: "ENCRYPTION",
  /** Entity already exists */
  ENTITY_EXISTS: "ENTITY_EXISTS",
  /** Entity does not exist */
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  /** Keyring already exists */
  EXISTS: "EXISTS",
  /** Password import failed (invalid hash format) */
  IMPORT_FAILED: "IMPORT_FAILED",
  /** Unexpected server error */
  INTERNAL: "INTERNAL",
  /** Invalid argument */
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  /** Field value is invalid or field cannot be updated via this path */
  INVALID_FIELD: "INVALID_FIELD",
  /** Token is invalid, expired, or revoked */
  INVALID_TOKEN: "INVALID_TOKEN",
  /** Required field missing from request */
  MISSING_FIELD: "MISSING_FIELD",
  /** Namespace already exists */
  NAMESPACE_EXISTS: "NAMESPACE_EXISTS",
  /** Namespace is not empty (use FORCE to override) */
  NAMESPACE_NOT_EMPTY: "NAMESPACE_NOT_EMPTY",
  /** Namespace does not exist */
  NAMESPACE_NOT_FOUND: "NAMESPACE_NOT_FOUND",
  /** No active signing key available */
  NOKEY: "NOKEY",
  /** Keyring or key version not found */
  NOTFOUND: "NOTFOUND",
  /** No auth token provided on this connection */
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  /** Key or resource does not exist */
  NOT_FOUND: "NOT_FOUND",
  /** Server is not in READY state */
  NOT_READY: "NOT_READY",
  /** S3 object store operation failed */
  OBJECT_STORE: "OBJECT_STORE",
  /** Pipeline command failed, all commands rolled back */
  PIPELINE_ABORTED: "PIPELINE_ABORTED",
  /** Operation denied by keyring policy */
  POLICY: "POLICY",
  /** Key version is retired — use REWRAP */
  RETIRED: "RETIRED",
  /** Blob has been soft-revoked */
  REVOKED: "REVOKED",
  /** Schema already exists */
  SCHEMA_EXISTS: "SCHEMA_EXISTS",
  /** Schema does not exist */
  SCHEMA_NOT_FOUND: "SCHEMA_NOT_FOUND",
  /** Schema definition is invalid */
  SCHEMA_VALIDATION: "SCHEMA_VALIDATION",
  /** Blob has been crypto-shredded (unrecoverable) */
  SHREDDED: "SHREDDED",
  /** Failed to sign decision */
  SIGNING: "SIGNING",
  /** Backend storage error */
  STORAGE: "STORAGE",
  /** Refresh token reuse detected — entire family revoked */
  TOKEN_REUSE: "TOKEN_REUSE",
  /** Metadata validation failed against namespace schema */
  VALIDATION_FAILED: "VALIDATION_FAILED",
  /** Credential verification failed (wrong password) */
  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  /** Requested version does not exist */
  VERSION_NOTFOUND: "VERSION_NOTFOUND",
  /** Requested version does not exist */
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  /** Operation not supported for this keyring type */
  WRONGTYPE: "WRONGTYPE",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

/** Base error class for all ShrouDB operations. */
export class ShrouDBError extends Error {
  /** The error code from the server (e.g. "NOTFOUND", "DENIED"). */
  public readonly code: string;

  constructor(code: string, message: string) {
    super(`${code} ${message}`);
    this.name = "ShrouDBError";
    this.code = code;
  }

  /** @internal Create from a server error response. */
  static _fromServer(code: string, detail: string): ShrouDBError {
    return new ShrouDBError(code, detail);
  }
}
